<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InvestmentFundsSeeder extends Seeder
{
    public function run(): void
    {
        $funds = [
            [
                'name' => 'صندوق العقارات السكنية',
                'description' => 'صندوق متخصص في الاستثمار في العقارات السكنية النامية',
                'type' => 'real_estate',
                'min_investment' => 5000.00,
                'max_investment' => 500000.00,
                'expected_return' => 10.50,
                'duration' => '12 شهر',
                'risk_level' => 'low',
                'total_funded' => 2500000.00,
                'funding_goal' => 5000000.00,
                'investors_count' => 45,
                'manager' => 'شركة الأصول العقارية',
                'status' => 'active',
                'start_date' => now()->subMonths(6)->toDateString(),
                'end_date' => now()->addMonths(6)->toDateString(),
                'location' => 'الرياض، السعودية',
                'featured' => true,
                'created_at' => now()->subMonths(6),
                'updated_at' => now(),
            ],
            [
                'name' => 'صندوق التكنولوجيا الصحية',
                'description' => 'صندوق يستثمر في الشركات الناشئة في قطاع التكنولوجيا الصحية',
                'type' => 'technology',
                'min_investment' => 10000.00,
                'max_investment' => 1000000.00,
                'expected_return' => 15.20,
                'duration' => '24 شهر',
                'risk_level' => 'medium',
                'total_funded' => 1800000.00,
                'funding_goal' => 3000000.00,
                'investors_count' => 28,
                'manager' => 'مجموعة الاستثمار المبتكرة',
                'status' => 'active',
                'start_date' => now()->subMonths(3)->toDateString(),
                'end_date' => now()->addMonths(21)->toDateString(),
                'location' => 'دبي، الإمارات',
                'featured' => true,
                'created_at' => now()->subMonths(3),
                'updated_at' => now(),
            ],
            [
                'name' => 'صندوق الطاقة المتجدرة',
                'description' => 'صندوق مخصص للاستثمار في مشاريع الطاقة الشمسية والرياح',
                'type' => 'renewable_energy',
                'min_investment' => 7500.00,
                'max_investment' => 750000.00,
                'expected_return' => 12.80,
                'duration' => '36 شهر',
                'risk_level' => 'medium',
                'total_funded' => 1200000.00,
                'funding_goal' => 4000000.00,
                'investors_count' => 35,
                'manager' => 'الاستثمار المستدام',
                'status' => 'active',
                'start_date' => now()->subMonths(2)->toDateString(),
                'end_date' => now()->addMonths(34)->toDateString(),
                'location' => 'أبوظبي، الإمارات',
                'featured' => false,
                'created_at' => now()->subMonths(2),
                'updated_at' => now(),
            ],
            [
                'name' => 'صندوق التجارة الإلكترونية',
                'description' => 'صندوق يستثمر في المتاجر الإلكترونية الناشئة',
                'type' => 'ecommerce',
                'min_investment' => 2500.00,
                'max_investment' => 250000.00,
                'expected_return' => 14.50,
                'duration' => '18 شهر',
                'risk_level' => 'high',
                'total_funded' => 800000.00,
                'funding_goal' => 2000000.00,
                'investors_count' => 52,
                'manager' => 'رأس المال الرقمي',
                'status' => 'active',
                'start_date' => now()->subMonth()->toDateString(),
                'end_date' => now()->addMonths(17)->toDateString(),
                'location' => 'جدة، السعودية',
                'featured' => false,
                'created_at' => now()->subMonth(),
                'updated_at' => now(),
            ],
            [
                'name' => 'صندوق التعليم والتدريب',
                'description' => 'صندوق يستثمر في شركات التعليم والتدريب والتطوير المهني',
                'type' => 'education',
                'min_investment' => 3000.00,
                'max_investment' => 300000.00,
                'expected_return' => 9.80,
                'duration' => '24 شهر',
                'risk_level' => 'low',
                'total_funded' => 1500000.00,
                'funding_goal' => 3000000.00,
                'investors_count' => 67,
                'manager' => 'الاستثمار في المعرفة',
                'status' => 'active',
                'start_date' => now()->subWeeks(2)->toDateString(),
                'end_date' => now()->addMonths(22)->toDateString(),
                'location' => 'القاهرة، مصر',
                'featured' => true,
                'created_at' => now()->subWeeks(2),
                'updated_at' => now(),
            ],
        ];

        DB::table('investment_funds')->insert($funds);
    }
}
