@extends('layouts.agent')

@section('title', 'Appointment Calendar')

@section('content')
<div class="container-fluid">
    <!-- Page Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h1 class="h3 mb-0">Appointment Calendar</h1>
            <p class="text-muted">View and manage your appointments in calendar format</p>
        </div>
        <div class="d-flex gap-2">
            <a href="{{ route('agent.appointments.create') }}" class="btn btn-primary">
                <i class="fas fa-plus me-2"></i>New Appointment
            </a>
            <a href="{{ route('agent.appointments.index') }}" class="btn btn-outline-secondary">
                <i class="fas fa-list me-2"></i>List View
            </a>
        </div>
    </div>

    <!-- Calendar Controls -->
    <div class="card mb-4">
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col-md-3">
                    <button class="btn btn-outline-primary" id="prevMonth">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <button class="btn btn-outline-primary ms-2" id="nextMonth">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
                <div class="col-md-6 text-center">
                    <h4 id="currentMonth" class="mb-0"></h4>
                </div>
                <div class="col-md-3 text-end">
                    <button class="btn btn-primary" id="todayBtn">Today</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Calendar Grid -->
    <div class="card">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-bordered calendar-table mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="text-center">Sun</th>
                            <th class="text-center">Mon</th>
                            <th class="text-center">Tue</th>
                            <th class="text-center">Wed</th>
                            <th class="text-center">Thu</th>
                            <th class="text-center">Fri</th>
                            <th class="text-center">Sat</th>
                        </tr>
                    </thead>
                    <tbody id="calendarBody">
                        <!-- Calendar days will be generated by JavaScript -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Appointment Details Modal -->
    <div class="modal fade" id="appointmentModal" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Appointment Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body" id="appointmentDetails">
                    <!-- Appointment details will be loaded here -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a href="#" class="btn btn-primary" id="editAppointmentBtn">Edit</a>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.calendar-table {
    table-layout: fixed;
}

.calendar-table th,
.calendar-table td {
    width: 14.28%;
    height: 100px;
    vertical-align: top;
    text-align: left;
    padding: 8px;
}

.calendar-day {
    cursor: pointer;
    transition: background-color 0.2s;
}

.calendar-day:hover {
    background-color: #f8f9fa;
}

.calendar-day-number {
    font-weight: bold;
    margin-bottom: 5px;
}

.calendar-day-today {
    background-color: #e3f2fd;
}

.calendar-day-weekend {
    background-color: #f5f5f5;
}

.appointment-item {
    font-size: 11px;
    padding: 2px 4px;
    margin: 1px 0;
    border-radius: 3px;
    cursor: pointer;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.appointment-scheduled {
    background-color: #007bff;
    color: white;
}

.appointment-completed {
    background-color: #28a745;
    color: white;
}

.appointment-cancelled {
    background-color: #dc3545;
    color: white;
}

.appointment-pending {
    background-color: #ffc107;
    color: black;
}
</style>
@endsection

@push('scripts')
<script>
let currentDate = new Date();
let currentMonth = currentDate.getMonth();
let currentYear = currentDate.getFullYear();

function generateCalendar(year, month) {
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const prevDaysInMonth = new Date(year, month, 0).getDate();
    
    let html = '';
    let date = 1;
    
    // Previous month days
    for (let i = firstDay - 1; i >= 0; i--) {
        const day = prevDaysInMonth - i;
        html += `<td class="calendar-day calendar-day-weekend text-muted">${day}</td>`;
    }
    
    // Current month days
    for (let i = firstDay; i < firstDay + daysInMonth; i++) {
        if (i % 7 === 0) html += '</tr><tr>';
        
        const isToday = year === new Date().getFullYear() && 
                        month === new Date().getMonth() && 
                        date === new Date().getDate();
        const isWeekend = i % 7 === 0 || i % 7 === 6;
        
        html += `<td class="calendar-day ${isToday ? 'calendar-day-today' : ''} ${isWeekend ? 'calendar-day-weekend' : ''}" data-date="${year}-${month + 1}-${date}">`;
        html += `<div class="calendar-day-number">${date}</div>`;
        html += `<div id="appointments-${year}-${month + 1}-${date}"></div>`;
        html += `</td>`;
        
        date++;
    }
    
    // Next month days
    const remainingDays = 42 - (firstDay + daysInMonth);
    for (let i = 1; i <= remainingDays; i++) {
        html += `<td class="calendar-day calendar-day-weekend text-muted">${i}</td>`;
    }
    
    document.getElementById('calendarBody').innerHTML = html;
    
    // Update month display
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                        'July', 'August', 'September', 'October', 'November', 'December'];
    document.getElementById('currentMonth').textContent = `${monthNames[month]} ${year}`;
    
    // Load appointments for current month
    loadAppointments(year, month);
}

function loadAppointments(year, month) {
    fetch(`/agent/appointments/calendar-data?year=${year}&month=${month + 1}`)
        .then(response => response.json())
        .then(data => {
            data.appointments.forEach(appointment => {
                const date = new Date(appointment.start_datetime);
                const dateKey = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
                const container = document.getElementById(`appointments-${dateKey}`);
                
                if (container) {
                    const appointmentEl = document.createElement('div');
                    appointmentEl.className = `appointment-item appointment-${appointment.status}`;
                    appointmentEl.textContent = `${formatTime(appointment.start_datetime)} - ${appointment.title}`;
                    appointmentEl.onclick = () => showAppointmentDetails(appointment.id);
                    container.appendChild(appointmentEl);
                }
            });
        })
        .catch(error => console.error('Error loading appointments:', error));
}

function formatTime(datetime) {
    const date = new Date(datetime);
    return date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
}

function showAppointmentDetails(appointmentId) {
    fetch(`/agent/appointments/${appointmentId}`)
        .then(response => response.text())
        .then(html => {
            document.getElementById('appointmentDetails').innerHTML = html;
            document.getElementById('editAppointmentBtn').href = `/agent/appointments/${appointmentId}/edit`;
            new bootstrap.Modal(document.getElementById('appointmentModal')).show();
        })
        .catch(error => console.error('Error loading appointment details:', error));
}

// Event listeners
document.getElementById('prevMonth').addEventListener('click', () => {
    currentMonth--;
    if (currentMonth < 0) {
        currentMonth = 11;
        currentYear--;
    }
    generateCalendar(currentYear, currentMonth);
});

document.getElementById('nextMonth').addEventListener('click', () => {
    currentMonth++;
    if (currentMonth > 11) {
        currentMonth = 0;
        currentYear++;
    }
    generateCalendar(currentYear, currentMonth);
});

document.getElementById('todayBtn').addEventListener('click', () => {
    const today = new Date();
    currentMonth = today.getMonth();
    currentYear = today.getFullYear();
    generateCalendar(currentYear, currentMonth);
});

// Initialize calendar
generateCalendar(currentYear, currentMonth);
</script>
@endpush
