@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h1 class="h3 mb-0">الجدول الزمني - {{ $project->name }}</h1>
            <p class="text-muted mb-0">عرض مراحل ومهام المشروع على شكل جدول جانت</p>
        </div>
        <div class="btn-group">
            <a href="{{ route('projects.show', $project) }}" class="btn btn-outline-secondary">
                <i class="fas fa-arrow-right"></i> العودة للمشروع
            </a>
            <button type="button" class="btn btn-outline-primary" onclick="printGantt()">
                <i class="fas fa-print"></i> طباعة
            </button>
        </div>
    </div>

    <!-- Project Timeline Info -->
    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="text-center">
                        <h5 class="text-primary">{{ $project->start_date->format('Y-m-d') }}</h5>
                        <p class="mb-0">تاريخ البدء</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="text-center">
                        <h5 class="text-danger">{{ $project->end_date->format('Y-m-d') }}</h5>
                        <p class="mb-0">تاريخ الانتهاء</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="text-center">
                        <h5 class="text-info">{{ $project->start_date->diffInDays($project->end_date) }}</h5>
                        <p class="mb-0">إجمالي الأيام</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="text-center">
                        <h5 class="text-success">{{ $project->getProgressPercentage() }}%</h5>
                        <p class="mb-0">نسبة التقدم</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Gantt Chart -->
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="card-title mb-0">الجدول الزمني</h5>
            <div class="btn-group btn-group-sm">
                <button type="button" class="btn btn-outline-primary" onclick="zoomIn()">
                    <i class="fas fa-search-plus"></i>
                </button>
                <button type="button" class="btn btn-outline-primary" onclick="zoomOut()">
                    <i class="fas fa-search-minus"></i>
                </button>
                <button type="button" class="btn btn-outline-primary" onclick="resetZoom()">
                    <i class="fas fa-compress"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div id="gantt-container" style="overflow-x: auto; overflow-y: auto; height: 500px;">
                <div id="gantt-chart" style="min-width: 1000px; position: relative;">
                    <!-- Timeline Header -->
                    <div class="gantt-header" style="display: flex; background: #f8f9fa; border-bottom: 1px solid #dee2e6; position: sticky; top: 0; z-index: 10;">
                        <div style="width: 250px; padding: 10px; border-left: 1px solid #dee2e6; font-weight: bold;">
                            المهمة/المرحلة
                        </div>
                        <div id="timeline-header" style="flex: 1; display: flex;">
                            <!-- Timeline months will be generated by JavaScript -->
                        </div>
                    </div>
                    
                    <!-- Gantt Rows -->
                    <div id="gantt-rows">
                        @foreach($project->phases as $phase)
                            <div class="gantt-row" data-type="phase" data-id="{{ $phase->id }}">
                                <div class="gantt-label" style="width: 250px; padding: 10px; border-right: 1px solid #dee2e6; background: #f8f9fa;">
                                    <strong>{{ $phase->name }}</strong>
                                    <br><small class="text-muted">{{ $phase->progress_percentage }}% تقدم</small>
                                </div>
                                <div class="gantt-timeline" style="flex: 1; position: relative; height: 40px;">
                                    <div class="gantt-bar phase-bar" 
                                         style="position: absolute; 
                                                background: #007bff; 
                                                height: 30px; 
                                                top: 5px;
                                                left: {{ $this->calculatePosition($phase->start_date, $project->start_date, $project->end_date) }}%;
                                                width: {{ $this->calculateWidth($phase->start_date, $phase->end_date, $project->start_date, $project->end_date) }}%;
                                                border-radius: 4px;
                                                display: flex;
                                                align-items: center;
                                                justify-content: center;
                                                color: white;
                                                font-size: 12px;">
                                        {{ $phase->name }}
                                    </div>
                                </div>
                            </div>
                            
                            @foreach($phase->tasks as $task)
                                <div class="gantt-row" data-type="task" data-id="{{ $task->id }}" style="background: #fafafa;">
                                    <div class="gantt-label" style="width: 250px; padding: 10px 10px 10px 30px; border-right: 1px solid #dee2e6;">
                                        {{ $task->name }}
                                        <br><small class="text-muted">
                                            @if($task->assignee)
                                                <i class="fas fa-user"></i> {{ $task->assignee->name }}
                                            @endif
                                        </small>
                                    </div>
                                    <div class="gantt-timeline" style="flex: 1; position: relative; height: 35px;">
                                        <div class="gantt-bar task-bar" 
                                             style="position: absolute; 
                                                    background: {{ $task->status == 'completed' ? '#28a745' : ($task->status == 'in_progress' ? '#ffc107' : '#6c757d') }}; 
                                                    height: 25px; 
                                                    top: 5px;
                                                    left: {{ $this->calculatePosition($task->start_date, $project->start_date, $project->end_date) }}%;
                                                    width: {{ $this->calculateWidth($task->start_date, $task->due_date, $project->start_date, $project->end_date) }}%;
                                                    border-radius: 3px;
                                                    display: flex;
                                                    align-items: center;
                                                    justify-content: center;
                                                    color: white;
                                                    font-size: 11px;
                                                    cursor: pointer;"
                                             title="{{ $task->name }} - {{ $task->start_date->format('Y-m-d') }} إلى {{ $task->due_date->format('Y-m-d') }}"
                                             onclick="showTaskDetails({{ $task->id }})">
                                            {{ $task->progress_percentage }}%
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Legend -->
    <div class="card mt-4">
        <div class="card-body">
            <h6 class="card-title">مفتاح الجدول</h6>
            <div class="row">
                <div class="col-md-3">
                    <div class="d-flex align-items-center">
                        <div style="width: 20px; height: 15px; background: #007bff; border-radius: 3px; margin-left: 10px;"></div>
                        <span>المراحل</span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="d-flex align-items-center">
                        <div style="width: 20px; height: 15px; background: #28a745; border-radius: 3px; margin-left: 10px;"></div>
                        <span>مهام مكتملة</span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="d-flex align-items-center">
                        <div style="width: 20px; height: 15px; background: #ffc107; border-radius: 3px; margin-left: 10px;"></div>
                        <span>مهام قيد التنفيذ</span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="d-flex align-items-center">
                        <div style="width: 20px; height: 15px; background: #6c757d; border-radius: 3px; margin-left: 10px;"></div>
                        <span>مهام لم تبدأ</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Task Details Modal -->
<div class="modal fade" id="taskModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">تفاصيل المهمة</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="taskDetails">
                <!-- Task details will be loaded here -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>
            </div>
        </div>
    </div>
</div>

@php
function calculatePosition($startDate, $projectStart, $projectEnd) {
    $totalDays = $projectStart->diffInDays($projectEnd);
    $startDays = $projectStart->diffInDays($startDate);
    return ($startDays / $totalDays) * 100;
}

function calculateWidth($startDate, $endDate, $projectStart, $projectEnd) {
    $totalDays = $projectStart->diffInDays($projectEnd);
    $taskDays = $startDate->diffInDays($endDate);
    return ($taskDays / $totalDays) * 100;
}
@endphp

<script>
document.addEventListener('DOMContentLoaded', function() {
    initializeGanttChart();
});

function initializeGanttChart() {
    const projectStart = new Date('{{ $project->start_date->format('Y-m-d') }}');
    const projectEnd = new Date('{{ $project->end_date->format('Y-m-d') }}');
    const totalDays = Math.ceil((projectEnd - projectStart) / (1000 * 60 * 60 * 24));
    
    // Generate timeline header
    const timelineHeader = document.getElementById('timeline-header');
    const dayWidth = 100 / totalDays;
    
    // Generate months
    let currentDate = new Date(projectStart);
    while (currentDate <= projectEnd) {
        const monthStart = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);
        const monthEnd = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0);
        
        const monthWidth = Math.min((monthEnd - monthStart) / (1000 * 60 * 60 * 24), totalDays) * dayWidth;
        
        const monthDiv = document.createElement('div');
        monthDiv.style.width = monthWidth + '%';
        monthDiv.style.padding = '10px';
        monthDiv.style.borderLeft = '1px solid #dee2e6';
        monthDiv.style.textAlign = 'center';
        monthDiv.style.fontSize = '12px';
        monthDiv.innerHTML = currentDate.toLocaleDateString('ar-SA', { month: 'short', year: 'numeric' });
        
        timelineHeader.appendChild(monthDiv);
        currentDate.setMonth(currentDate.getMonth() + 1);
    }
}

function showTaskDetails(taskId) {
    // Load task details via AJAX
    fetch(`/projects/tasks/${taskId}/details`)
        .then(response => response.json())
        .then(data => {
            document.getElementById('taskDetails').innerHTML = `
                <h6>${data.name}</h6>
                <p><strong>الوصف:</strong> ${data.description || 'لا يوجد وصف'}</p>
                <p><strong>الحالة:</strong> ${data.status}</p>
                <p><strong>الأولوية:</strong> ${data.priority}</p>
                <p><strong>التقدم:</strong> ${data.progress_percentage}%</p>
                <p><strong>تاريخ البدء:</strong> ${data.start_date}</p>
                <p><strong>تاريخ الانتهاء:</strong> ${data.due_date}</p>
                <p><strong>المسؤول:</strong> ${data.assignee_name || 'غير محدد'}</p>
            `;
            new bootstrap.Modal(document.getElementById('taskModal')).show();
        })
        .catch(error => console.error('Error loading task details:', error));
}

function zoomIn() {
    const container = document.getElementById('gantt-container');
    const currentZoom = container.style.zoom || 1;
    container.style.zoom = Math.min(currentZoom * 1.2, 3);
}

function zoomOut() {
    const container = document.getElementById('gantt-container');
    const currentZoom = container.style.zoom || 1;
    container.style.zoom = Math.max(currentZoom / 1.2, 0.5);
}

function resetZoom() {
    document.getElementById('gantt-container').style.zoom = 1;
}

function printGantt() {
    window.print();
}
</script>

<style>
@media print {
    .btn-group, .card-header .btn-group {
        display: none !important;
    }
    
    #gantt-container {
        overflow: visible !important;
        height: auto !important;
    }
    
    .gantt-header {
        position: relative !important;
    }
}

.gantt-row:hover {
    background: #f0f8ff !important;
}

.gantt-bar:hover {
    opacity: 0.8;
    transform: translateY(-1px);
    transition: all 0.2s ease;
}
</style>
@endsection
