<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AnalyzePropertyImageRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            'property_id' => 'required|exists:properties,id',
            'image' => 'required|file|image|mimes:jpeg,jpg,png,gif,bmp,tiff|max:10240',
            'analysis_type' => 'required|in:room_detection,object_recognition,quality_assessment,aesthetic_analysis,renovation_analysis,staging_analysis,comprehensive',
            'detection_method' => 'required|in:ai_pattern_recognition,manual_review,user_report,automated_monitoring,behavioral_analysis',
            'room_types' => 'nullable|array',
            'room_types.*.type' => 'required|string|max:50',
            'room_types.*.confidence' => 'required|numeric|min:0|max:100',
            'room_types.*.area_percentage' => 'required|numeric|min:0|max:100',
            'quality_assessment' => 'nullable|array',
            'quality_assessment.overall_score' => 'nullable|numeric|min:0|max:10',
            'quality_assessment.resolution' => 'nullable|numeric|min:1920|max:7680',
            'quality_assessment.lighting_quality' => 'nullable|numeric|min:0|max:100',
            'quality_assessment.color_balance' => 'nullable|numeric|min:0|max:100',
            'quality_assessment.composition_score' => 'nullable|numeric|min:0|max:100',
            'quality_assessment.clutter_level' => 'nullable|numeric|min:0|max:100',
            'aesthetic_appeal' => 'nullable|numeric|min:0|max:10',
            'aesthetic_appeal.style_consistency' => 'nullable|numeric|min:0|max:100',
            'aesthetic_appeal.market_appeal' => 'nullable|numeric|min:0|max:10',
            'lighting_analysis' => 'nullable|array',
            'lighting_analysis.brightness_level' => 'nullable|numeric|min:0|max:100',
            'lighting_analysis.natural_light_ratio' => 'nullable|numeric|min:0|max:1',
            'lighting_analysis.lighting_distribution' => 'nullable|string|max:100',
            'lighting_analysis.shadow_analysis' => 'nullable|string|max:500',
            'lighting_analysis.artificial_lighting' => 'nullable|boolean',
            'color_analysis' => 'nullable|array',
            'color_analysis.dominant_colors' => 'nullable|array',
            'color_analysis.color_scheme' => 'nullable|string|max:50',
            'color_analysis.contrast_level' => 'nullable|numeric|min:0|max:100',
            'color_analysis.harmony_score' => 'nullable|numeric|min:0|max:100',
            'composition_analysis' => 'nullable|array',
            'composition_analysis.balance_score' => 'nullable|numeric|min:0|max:100',
            'composition_analysis.rule_of_thirds_score' => 'nullable|numeric|min:0|max:100',
            'composition_analysis.symmetry_score' => 'nullable|numeric|min:0|max:100',
            'composition_analysis.focal_point_strength' => 'nullable|numeric|min:0|max:100',
            'composition_analysis.depth_perception' => 'nullable|numeric|min:0|max:10',
            'clutter_analysis' => 'nullable|array',
            'clutter_analysis.clutter_score' => 'nullable|numeric|min:0|max:100',
            'clutter_analysis.clutter_areas' => 'nullable|array',
            'clutter_analysis.organization_score' => 'nullable|numeric|min:0|max:100',
            'renovation_suggestions' => 'nullable|array',
            'renovation_suggestions.*.type' => 'required|string|max:100',
            'renovation_suggestions.description' => 'nullable|string|max:500',
            'renovation_suggestions.priority' => 'required|in:low,medium,high',
            'renovation_suggestions.estimated_cost' => 'required|numeric|min:0',
            'renovation_suggestions.impact_score' => 'required|numeric|min:0|max:100',
            'staging_recommendations' => 'nullable|array',
            'staging_recommendations.*.recommendation' => 'required|string|max:300',
            'staging_recommendations.description' => 'nullable|string|max:500',
            'staging_recommendations.priority' => 'required|in:low,medium,high',
            'staging_recommendations.style' => 'required|string|max:50',
            'staging_recommendations.color_scheme' => 'required|string|max:50',
            'staging_recommendations.furniture_style' => 'required|string|max:50',
            'staging_recommendations.target_audience' => 'required|string|max:50',
            'staging_recommendations.budget_range' => 'required|string|max:50',
            'image_enhancements' => 'nullable|array',
            'image_enhancements.*.enhancement' => 'required|string|max:100',
            'image_enhancements.*.strength' => 'required|integer|min:1|max:10',
            'image_enhancements.description' => 'nullable|string|max:300',
            'analysis_metadata' => 'nullable|array',
            'analysis_metadata.processing_time' => 'nullable|numeric|min:0',
            'analysis_metadata.data_points_analyzed' => 'nullable|integer|min:0',
            'analysis_metadata.model_version' => 'nullable|string|max:50',
            'analysis_metadata.confidence_factors' => 'nullable|array',
            'confidence_level' => 'required|numeric|min:0|max:1',
            'priority_level' => 'nullable|in:low,medium,high,critical',
            'notes' => 'nullable|string|max:1000',
            'custom_analysis_instructions' => 'nullable|string|max:1000',
            'include_object_detection' => 'boolean',
            'include_room_detection' => 'boolean',
            'include_quality_assessment' => 'boolean',
            'include_aesthetic_analysis' => 'boolean',
            'include_lighting_analysis' => 'boolean',
            'include_color_analysis' => 'boolean',
            'include_composition_analysis' => 'boolean',
            'include_clutter_analysis' => 'boolean',
            'include_renovation_suggestions' => 'boolean',
            'include_staging_recommendations' => 'boolean',
            'include_image_enhancements' => 'boolean',
            'batch_analysis' => 'boolean',
            'property_ids' => 'required_if:batch_analysis|array|min:1|max:10',
            'property_ids.*' => 'exists:properties,id',
            'comparison_property_id' => 'nullable|exists:properties,id',
            'analysis_depth' => 'nullable|in:basic,standard,detailed,comprehensive',
        ];
    }

    /**
     * Get custom error messages for validation rules.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'property_id.required' => 'يجب اختيار العقار',
            'property_id.exists' => 'العقار المحدد غير موجود',
            'image.required' => 'يجب رفع الصورة',
            'image.file' => 'يجب أن يكون الملف صورة',
            'image.mimes' => 'يجب أن يكون الملف من نوع: jpeg, jpg, png, gif, bmp, tiff',
            'image.max' => 'حجم الملف لا يمكن أن يتجاوز 10 ميجابايت',
            'analysis_type.required' => 'يجب اختيار نوع التحليل',
            'analysis_type.in' => 'نوع التحليل غير صالحح',
            'detection_method.required' => 'يجب اختيار طريقة الكشف',
            'detection_method.in' => 'طريقة الكشف غير صالحة',
            'room_types.array' => 'أنواع الغرف يجب أن تكون مصفوفة',
            'room_types.*.type.required' => 'نوع الغرفة مطلوب',
            'room_types.*.type.string' => 'نوع الغرفة يجب أن يكون نصاً',
            'room_types.*.type.max' => 'نوع الغرفة لا يمكن أن يتجاوز 50 حرف',
            'room_types.*.confidence.numeric' => 'مستوى الثقة مطلوب',
            'room_types.*.confidence.min' => 'مستوى الثقة لا يمكن أن يكون أقل من 0',
            'room_types.*.confidence.max' => 'مستوى الثقة لا يمكن أن يتجاوز 100',
            'room_types.*.area_percentage.numeric' => 'نسبة المساحة مطلوبة',
            'room_types.*.area_percentage.min' => 'نسبة المساحة لا يمكن أن تكون أقل من 0',
            'room_types.*.area_percentage.max' => 'نسبة المساحة لا يمكن أن تتعد 100',
            'quality_assessment.overall_score.numeric' => 'مستوى الجودة الإجمالي مطلوب',
            'quality_assessment.overall_score.min' => 'مستوى الجودة الإجمالي لا يمكن أن يكون أقل من 0',
            'quality_assessment.overall_score.max' => 'مستوى الجودة الإجمالي لا يمكن أن يتجاوز 10',
            'quality_assessment.resolution.numeric' => 'دقة الدقة مطلوبة',
            'quality_assessment.resolution.min' => 'دقة الدقة لا يمكن أن تكون أقل من 1920',
            'quality_assessment.resolution.max' => 'دقة الدقة لا يمكن أن تتعد 7680',
            'quality_assessment.lighting_quality.numeric' => 'جودة الإضاءة مطلوبة',
            'quality_assessment.lighting_quality.min' => 'جودة الإضاءة لا يمكن أن تكون أقل من 0',
            'quality_assessment.lighting_quality.max' => 'جودة الإضاءة لا يمكن أن تتعد 100',
            'quality_assessment.color_balance.numeric' => 'توازن الألوان مطلوب',
            'quality_assessment.color_balance.min' => 'توازن الألوان لا يمكن أن يكون أقل من 0',
            'quality_assessment.color_balance.max' => 'توازن الألوان لا يمكن أن تتعد 100',
            'quality_assessment.composition_score.numeric' => 'درجة التكوين مطلوبة',
            'quality_assessment.composition_score.min' => 'درجة التكوين لا يمكن أن تكون أقل من 0',
            'quality_assessment.composition_score.max' => 'درجة التكوين لا يمكن أن تتعد 100',
            'quality_assessment.rule_of_thirds_score.numeric' => 'قاعدة الثلث مطلوبة',
            'quality_assessment.rule_of_thirds_score.min' => 'قاعدة الثلث لا يمكن أن تكون أقل من 0',
            'quality_assessment.rule_of_thirds_score.max' => 'قاعدة الثلث لا يمكن أن تتعد 100',
            'quality_assessment.symmetry_score.numeric' => 'التوازن المتماثل مطلوب',
            'quality_assessment.symmetry_score.min' => 'التوازن المتماثل لا يمكن أن يكون أقل من 0',
            'quality_assessment.symmetry_score.max' => 'التوازن المتماثل لا يمكن أن تتعد 100',
            'quality_assessment.focal_point_strength.numeric' => 'قوة النقطة المحورية مطلوبة',
            'quality_assessment.focal_point_strength.min' => 'قوة النقطة المحورية لا يمكن أن يكون أقل من 0',
            'quality_assessment.focal_point_strength.max' => 'قوة النقطة المحورية لا يمكن أن تتعد 100',
            'quality_assessment.depth_perception.numeric' => 'عمق الإدراك مطلوب',
            'quality_assessment.depth_perception.min' => 'عمق الإدراك لا يمكن أن يكون أقل من 0',
            'quality_assessment.depth_perception.max' => 'عمق الإدراك لا يمكن أن يتعد 10',
            'clutter_analysis.clutter_score.numeric' => 'درجة الفوضى مطلوبة',
            'clutter_analysis.clutter_score.min' => 'درجة الفوضى لا يمكن أن يكون أقل من 0',
            'clutter_analysis.clutter_score.max' => 'درجة الفوضى لا يمكن أن تتعد 100',
            'clutter_analysis.organization_score.numeric' => 'درجة التنظيم مطلوبة',
            'clutter_analysis.organization_score.min' => 'درجة التنظيم لا يمكن أن يكون أقل من 0',
            'clutter_analysis.organization_score.max' => 'درجة التنظيم لا يمكن أن تتعد 100',
            'renovation_suggestions.array' => 'اقتراحات التحسين يجب أن تكون مصفوفة',
            'renovation_suggestions.*.type.required' => 'نوع التحسين مطلوب',
            'renovation_suggestions.*.type.string' => 'نوع التحسين يجب أن يكون نصاً',
            'renovation_suggestions.*.type.max' => 'نوع التحسين لا يمكن أن يتجاوز 100 حرف',
            'renovation_suggestions.description.string' => 'وصف التحسين مطلوب',
            'renovation_suggestions.description.max' => 'وصف التحسين لا يمكن أن يتجاوز 500 حرف',
            'renovation_suggestions.priority.in' => 'مستوى الأولوية غير صالحح',
            'renovation_suggestions.priority.max' => 'مستوى الأولوية غير صالحح',
            'renovation_suggestions.estimated_cost.numeric' => 'التكلفة التقديرية مطلوبة',
            'renovation_suggestions.estimated_cost.min' => 'التكلفة التقديرية لا يمكن أن تكون سالبة',
            'renovation_suggestions.impact_score.numeric' => 'تأثير التحسين مطلوب',
            'renovation_suggestions.impact_score.min' => 'تأثير التحسين لا يمكن أن يكون أقل من 0',
            'renovation_suggestions.impact_score.max' => 'تأثير التحسين لا يمكن أن يتجاوز 100',
            'staging_recommendations.array' => 'توصيات التنسيق يجب أن تكون مصفوفة',
            'staging_recommendations.*.recommendation.required' => 'التوصية مطلوبة',
            'staging_recommendations.*.recommendation.string' => 'التوصية يجب أن تكون نصاً',
            'staging_recommendations.*.recommendation.max' => 'التوصية لا يمكن أن يتجاوز 300 حرف',
            'staging_recommendations.priority.in' => 'مستوى الأولوية غير صالحح',
            'staging_recommendations.priority.max' => 'مستوى الأولوية غير صالحح',
            'staging_recommendations.style.required' => 'نمطط التنسيق مطلوب',
            'staging_recommendations.style.string' => 'نمطط التنسيق يجب أن يكون نصاً',
            'staging_recommendations.style.max' => 'نمطط التنسيق لا يمكن أن يتجاوز 50 حرف',
            'staging_recommendations.color_scheme.required' => 'مخط الألوان مطلوب',
            'staging_recommendations.color_scheme.string' => 'خط الألوان يجب أن يكون نصاً',
            'staging_recommendations.color_scheme.max' => 'خط الألوان لا يمكن أن يتجاوز 50 حرف',
            'staging_recommendations.furniture_style.required' => 'نمطط الأثاث مطلوب',
            'staging_recommendations.furniture_style.string' => 'نمطط الأثاث يجب أن يكون نصاً',
            'staging_recommendations.furniture_style.max' => 'نمطط الأثاث لا يمكن أن يتجاوز 50 حرف',
            'staging_recommendations.target_audience.required' => 'الجمهور المستهدف مطلوب',
            'staging_recommendations.target_audience.string' => 'الجمهور المستهدف يجب أن يكون نصاً',
            'staging_recommendations.target_audience.max' => 'الجمهور المستهدف لا يمكن أن يتجاوز 50 حرف',
            'staging_recommendations.budget_range.required' => 'نطاق الميزانية مطلوب',
            'staging_recommendations.budget_range.string' => 'نطاق الميزانية يجب أن يكون نصاً',
            'staging_recommendations.budget_range.max' => 'نطاق الميزانية لا يمكن أن يتجاوز 50 حرف',
            'image_enhancements.array' => 'تحسينات الصور يجب أن تكون مصفوفة',
            'image_enhancements.*.enhancement.required' => 'نوع التحسين مطلوب',
            'image_enhancements.*.enhancement.string' => 'نوع التحسين مطلوب',
            'image_enhancements.*.enhancement.max' => 'نوع التحسين لا يمكن أن يتجاوز 100 حرف',
            'image_enhancements.*.strength.required' => 'قوة التحسين مطلوب',
            'image_enhancements.*.strength.min' => 'قوة التحسين لا يمكن أن يكون أقل من 1',
            'image_enhancements.*.strength.max' => 'قوة التحسين لا يمكن أن يتجاوز 10',
            'image_enhancements.*.description.string' => 'وصف التحسين مطلوب',
            'image_enhancements.*.description.max' => 'وصف التحسين لا يمكن أن يتجاوز 300 حرف',
            'confidence_level.required' => 'مستوى الثقة مطلوب',
            'confidence_level.numeric' => 'مستوى الثقة يجب أن يكون رقماً',
            'confidence_level.min' => 'مستوى الثقة لا يمكن أن يكون أقل من 0',
            'confidence_level.max' => 'مستوى الثقة لا يمكن أن يتجاوز 1',
            'priority_level.in' => 'مستوى الأولوية غير صالحح',
            'priority_level.max' => 'مستوى الأولوية غير صالحح',
            'batch_analysis.boolean' => 'وضعية التحليل الدفععي مطلوبة',
            'property_ids.required_if' => 'العقارات مطلوبة للتحليل الدفععي',
            'property_ids.array' => 'العقارات يجب أن تكون مصفوفة',
            'property_ids.*.exists' => 'أحد العقارات غير موجود',
            'comparison_property_id.exists' => 'العقار المقارن غير موجود',
            'analysis_depth.in' => 'عمق التحليل غير صالحح',
            'custom_analysis_instructions.string' => 'تعليمات التحليل المخصصة يجب أن تكون نصاً',
            'custom_analysis_instructions.max' => 'تعليمات التحليل لا يمكن أن تتعد 1000 حرف',
        ];
    }

    /**
     * Get custom attribute names for validation errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return [
            'property_id' => 'العقار',
            'image' => 'الصورة',
            'analysis_type' => 'نوع التحليل',
            'detection_method' => 'طريقة الكشف',
            'room_types' => 'أنواع الغرف',
            'room_types.type' => 'نوع الغرفة',
            'room_types.confidence' => 'مستوى الثقة',
            'room_types.area_percentage' => 'نسبة المساحة',
            'quality_assessment.overall_score' => 'مستوى الجودة الإجمالي',
            'quality_assessment.resolution' => 'دقة الدقة',
            'quality_assessment.lighting_quality' => 'جودة الإضاءة',
            'quality_assessment.color_balance' => 'توازن الألوان',
            'quality_assessment.composition_score' => 'درجة التكوين',
            'quality_assessment.rule_of_thirds_score' => 'قاعدة الثلث',
            'quality_assessment.symmetry_score' => 'التوازن المتماثل',
            'quality_assessment.focal_point_strength' => 'قوة النقطة المحورية',
            'quality_assessment.depth_perception' => 'عمق الإدراك',
            'quality_assessment.aesthetic_appeal' => 'الجاذبية الجمالية',
            'quality_assessment.style_consistency' => 'تناسق النمط',
            'quality_assessment.market_appeal' => 'الجاذبية السوقية',
            'lighting_analysis.brightness_level' => 'مستوى سطوع الإضاءة',
            'lighting_analysis.natural_light_ratio' => 'نسبة الإضاءة الطبيعية',
            'lighting_analysis.lighting_distribution' => 'توزيع الإضاءة',
            'lighting_analysis.shadow_analysis' => 'تحليل الظلال',
            'lighting_analysis.artificial_lighting' => 'الإضاءة الاصطناعي',
            'color_analysis.dominant_colors' => 'الألوان الرئيسية',
            'color_analysis.color_scheme' => 'مخط الألوان',
            'color_analysis.contrast_level' => 'مستوى التباين',
            'color_analysis.harmony_score' => 'تناسق الألوان',
            'composition_analysis.balance_score' => 'توازن التكوين',
            'composition_analysis.rule_of_thirds_score' => 'قاعدة الثلث',
            'composition_analysis.symmetry_score' => 'التوازن المتماثل',
            'composition_analysis.focal_point_strength' => 'قوة النقطة المحورية',
            'composition_analysis.depth_perception' => 'عمق الإدراك',
            'clutter_analysis.clutter_score' => 'درجة الفوضى',
            'clutter_analysis.clutter_areas' => 'مناطق الفوضى',
            'clutter_analysis.organization_score' => 'درجة التنظيم',
            'renovation_suggestions' => 'اقتراحات التحسين',
            'renovation_suggestions.type' => 'نوع التحسين',
            'renovation_suggestions.description' => 'وصف التحسين',
            'renovation_suggestions.priority' => 'مستوى الأولوية',
            'renovation_suggestions.estimated_cost' => 'التكلفة التقديرية',
            'renovation_suggestions.impact_score' => 'تأثير التحسين',
            'staging_recommendations' => 'توصيات التنسيق',
            'staging_recommendations.recommendation' => 'التوصية',
            'staging_recommendations.priority' => 'مستوى الأولوية',
            'staging_recommendations.style' => 'نمطط التنسيق',
            'staging_recommendations.color_scheme' => 'خط الألوان',
            'staging_recommendations.furniture_style' => 'نمطط الأثاث',
            'staging_recommendations.target_audience' => 'الجمهور المستهدف',
            'staging_recommendations.budget_range' => 'نطاق الميزانية',
            'image_enhancements' => 'تحسينات الصور',
            'image_enhancements.enhancement' => 'نوع التحسين',
            'image_enhancements.strength' => 'قوة التحسين',
            'image_enhancements.description' => 'وصف التحسين',
            'confidence_level' => 'مستوى الثقة',
            'priority_level' => 'مستوى الأولوية',
            'notes' => 'ملاحظات',
            'custom_analysis_instructions' => 'تعليمات التحليل المخصصة',
            'batch_analysis' => 'وضعية التحليل الدفععي',
            'property_ids' => 'العقارات',
            'comparison_property_id' => 'العقار المقارن',
            'analysis_depth' => 'عمق التحليل',
        ];
    }
}
