<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class GenerateDescriptionRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            'property_id' => 'required|exists:properties,id',
            'description_type' => 'required|in:detailed,brief,marketing,technical,investment,luxury',
            'language' => 'required|in:ar,en',
            'tone' => 'required|in:professional,friendly,formal,casual,luxurious,persuasive',
            'target_audience' => 'required|in:families,young_professionals,retirees,investors,students,luxury_buyers,first_time_buyers',
            'property_features' => 'nullable|array',
            'property_features.*.feature' => 'required|string|max:200',
            'property_features.*.highlight' => 'required|boolean',
            'property_features.*.description' => 'nullable|string|max:500',
            'selling_points' => 'nullable|array',
            'selling_points.*.point' => 'required|string|max:300',
            'selling_points.*.emphasis' => 'required|in:low,medium,high',
            'call_to_action' => 'nullable|string|max:200',
            'seo_keywords' => 'nullable|array',
            'seo_keywords.*.keyword' => 'required|string|max:100',
            'seo_keywords.*.importance' => 'required|integer|min:1|max:10',
            'property_type' => 'nullable|string|max:50',
            'property_size' => 'nullable|numeric|min:1',
            'property_condition' => 'nullable|string|in:excellent,good,fair,poor,needs_renovation',
            'location_benefits' => 'nullable|array',
            'location_benefits.*.benefit' => 'required|string|max:200',
            'location_benefits.*.description' => 'nullable|string|max:500',
            'amenities' => 'nullable|array',
            'amenities.*.amenity' => 'required|string|max:100',
            'amenities.*.available' => 'required|boolean',
            'amenities.*.description' => 'nullable|string|max:300',
            'nearby_attractions' => 'nullable|array',
            'nearby_attractions.*.attraction' => 'required|string|max:200',
            'nearby_attractions.*.distance' => 'required|numeric|min:0|max:10',
            'nearby_attractions.*.description' => 'nullable|string|max:300',
            'style_preferences' => 'nullable|array',
            'style_preferences.*.style' => 'required|string|max:50',
            'style_preferences.*.color_scheme' => 'required|string|max:50',
            'style_preferences.*.furniture_style' => 'required|string|max:50',
            'content_length' => 'nullable|integer|min:50|max:2000',
            'include_highlights' => 'boolean',
            'include_call_to_action' => 'boolean',
            'include_seo_keywords' => 'boolean',
            'quality_level' => 'nullable|in:basic,standard,premium,premium',
            'engagement_prediction' => 'nullable|numeric|min:0|max:100',
            'target_word_count' => 'nullable|integer|min:100|max:2000',
            'readability_score' => 'nullable|numeric|min:0|max:10',
            'custom_instructions' => 'nullable|string|max:1000',
            'reference_descriptions' => 'nullable|array',
            'reference_descriptions.*.description' => 'required|string|max:500',
            'reference_descriptions.*.url' => 'nullable|url|max:500',
            'avoid_words' => 'nullable|array',
            'avoid_words.*.word' => 'required|string|max:100',
            'focus_areas' => 'nullable|array',
            'focus_areas.*.area' => 'required|string|max:200',
            'focus_areas.*.priority' => 'required|integer|min:1|max:10',
            'property_images' => 'nullable|array',
            'property_images.*.image' => 'required|file|image|mimes:jpeg,jpg,png,gif|max:10240',
            'property_images.*.primary' => 'boolean',
            'property_images.*.description' => 'nullable|string|max:200',
            'property_images.*.angle' => 'nullable|string|max:50',
            'property_images.*.room_type' => 'nullable|string|max:50',
            'generation_model' => 'nullable|string|max:50',
            'temperature' => 'nullable|numeric|min:0.1|max:2.0',
            'max_tokens' => 'nullable|integer|min:100|max:4000',
            'use_custom_prompt' => 'boolean',
            'custom_prompt' => 'nullable|string|max:2000',
            'batch_generation' => 'boolean',
            'property_ids' => 'required_if:batch_generation|array|min:1|max:10',
            'property_ids.*' => 'exists:properties,id',
            'template_id' => 'nullable|exists:ai_generated_descriptions,id',
            'variation_count' => 'nullable|integer|min:1|max:5',
            'a_b_testing' => 'boolean',
            'test_instructions' => 'nullable|string|max:1000',
        ];
    }

    /**
     * Get custom error messages for validation rules.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'property_id.required' => 'يجب اختيار العقار',
            'property_id.exists' => 'العقار المحدد غير موجود',
            'description_type.required' => 'يجب اختيار نوع الوصف',
            'description_type.in' => 'نوع الوصف غير صالحح',
            'language.required' => 'يجب اختيار اللغة',
            'language.in' => 'اللغة غير صالحة',
            'tone.required' => 'يجب اختيار نبرة الوصف',
            'tone.in' => 'نبرة الوصف غير صالحة',
            'target_audience.required' => 'يجب اختيار الجمهور المستهدف',
            'target_audience.in' => 'الجمهور المستهدف غير صالحح',
            'property_features.array' => 'ميزات العقار يجب أن تكون مصفوفة',
            'property_features.*.feature.required' => 'الميزة مطلوبة',
            'property_features.*.feature.string' => 'الميزة يجب أن تكون نصاً',
            'property_features.*.feature.max' => 'الميزة لا يمكن أن تتجاوز 200 حرف',
            'property_features.*.highlight.boolean' => 'تمييز الميزة مطلوب',
            'property_features.*.description.string' => 'وصف الميزة يجب أن يكون نصاً',
            'property_features.*.description.max' => 'وصف الميزة لا يمكن أن يتجاوز 500 حرف',
            'selling_points.array' => 'نقاط البيع يجب أن تكون مصفوفة',
            'selling_points.*.point.required' => 'نقطة البيع مطلوبة',
            'selling_points.*.point.string' => 'نقطة البيع يجب أن تكون نصاً',
            'selling_points.*.point.max' => 'نقطة البيع لا يمكن أن تتجاوز 300 حرف',
            'selling_points.*.point.emphasis.in' => 'مستوى التركيز غير صالحح',
            'call_to_action.string' => 'دعوة اتخاذ الإجراء يجب أن تكون نصاً',
            'call_to_action.max' => 'دعوة اتخاذ الإجراء لا يمكن أن تتجاوز 200 حرف',
            'seo_keywords.array' => 'كلمات SEO يجب أن تكون مصفوفة',
            'seo_keywords.*.keyword.required' => 'الكلمة المفتاحية مطلوبة',
            'seo_keywords.*.keyword.string' => 'الكلمة المفتاحية يجب أن تكون نصاً',
            'seo_keywords.*.keyword.max' => 'الكلمة المفتاحية لا يمكن أن تتجاوز 100 حرف',
            'seo_keywords.*.importance.integer' => 'أهمية الكلمة المفتاحية يجب أن تكون رقماً',
            'seo_keywords.*.importance.min' => 'أهمية الكلمة المفتاحية لا يمكن أن تكون أقل من 1',
            'seo_keywords.*.importance.max' => 'أهمية الكلمة المفتاحية لا يمكن أن تتجاوز 10',
            'property_type.string' => 'نوع العقار يجب أن يكون نصاً',
            'property_type.max' => 'نوع العقار لا يمكن أن يتجاوز 50 حرف',
            'property_size.numeric' => 'مساحة العقار يجب أن تكون رقماً',
            'property_size.min' => 'مساحة العقار لا يمكن أن تكون أقل من 1',
            'property_condition.in' => 'حالة العقار غير صالحة',
            'location_benefits.array' => 'مزايا الموقع يجب أن تكون مصفوفة',
            'location_benefits.*.benefit.required' => 'الميزة الموقع مطلوبة',
            'location_benefits.*.benefit.string' => 'الميزة الموقع يجب أن تكون نصاً',
            'location_benefits.*.benefit.max' => 'الميزة الموقع لا يمكن أن تتجاوز 200 حرف',
            'location_benefits.*.benefit.description.string' => 'وصف الميزة يجب أن يكون نصاً',
            'location_benefits.*.benefit.description.max' => 'وصف الميزة لا يمكن أن يتجاوز 500 حرف',
            'amenities.array' => 'المرافق يجب أن تكون مصفوفة',
            'amenities.*.amenity.required' => 'المرفق مطلوب',
            'amenities.*.amenity.string' => 'المرفق يجب أن يكون نصاً',
            'amenities.*.amenity.max' => 'المرفق لا يمكن أن يتجاوز 100 حرف',
            'amenities.*.available.boolean' => 'توفر المرفق مطلوب',
            'amenities.*.description.string' => 'وصف المرفق يجب أن يكون نصاً',
            'amenities.*.description.max' => 'وصف المرفق لا يمكن أن يتجاوز 300 حرف',
            'nearby_attractions.array' => 'المعالم القريبة يجب أن تكون مصفوفة',
            'nearby_attractions.*.attraction.required' => 'المعلم القريب مطلوب',
            'nearby_attractions.*.attraction.string' => 'المعلم القريب يجب أن يكون نصاً',
            'nearby_attractions.*.attraction.max' => 'المعلم القريب لا يمكن أن يتجاوز 200 حرف',
            'nearby_attractions.*.distance.numeric' => 'المسافة يجب أن تكون رقماً',
            'nearby_attractions.*.distance.min' => 'المسافة لا يمكن أن تكون أقل من 0',
            'nearby_attractions.*.distance.max' => 'المسافة لا يمكن أن تتجاوز 10 كم',
            'nearby_attractions.*.description.string' => 'وصف المعلم القريب يجب أن يكون نصاً',
            'nearby_attractions.*.description.max' => 'وصف المعلم القريب لا يمكن أن يتجاوز 300 حرف',
            'style_preferences.array' => 'تفضيلات النمط يجب أن تكون مصفوفة',
            'style_preferences.*.style.required' => 'النمط مطلوب',
            'style_preferences.*.style.string' => 'النمط يجب أن يكون نصاً',
            'style_preferences.*.style.max' => 'النمط لا يمكن أن يتجاوز 50 حرف',
            'style_preferences.*.color_scheme.required' => 'مخط الألوان مطلوب',
            'style_preferences.*.color_scheme.string' => 'مخط الألوان يجب أن يكون نصاً',
            'style_preferences.*.color_scheme.max' => 'مخط الألوان لا يمكن أن يتجاوز 50 حرف',
            'style_preferences.*.furniture_style.required' => 'نمط الأثاث مطلوب',
            'style_preferences.*.furniture_style.string' => 'نمط الأثاث يجب أن يكون نصاً',
            'style_preferences.*.furniture_style.max' => 'نمط الأثاث لا يمكن أن يتجاوز 50 حرف',
            'content_length.integer' => 'طول المحتوى يجب أن يكون رقماً',
            'content_length.min' => 'طول المحتوى لا يمكن أن يكون أقل من 50',
            'content_length.max' => 'طول المحتوى لا يمكن أن يتجاوز 2000 حرف',
            'quality_level.in' => 'مستوى الجودة غير صالحح',
            'engagement_prediction.numeric' => 'توقع التفاعل يجب أن يكون رقماً',
            'engagement_prediction.min' => 'توقع التفاعل لا يمكن أن يكون أقل من 0',
            'engagement_prediction.max' => 'توقع التفاعل لا يمكن أن يتجاوز 100',
            'target_word_count.integer' => 'عدد الكلمات المستهدف يجب أن يكون رقماً',
            'target_word_count.min' => 'عدد الكلمات المستهدف لا يمكن أن يكون أقل من 100',
            'target_word_count.max' => 'عدد الكلمات المستهدف لا يمكن أن يتجاوز 2000',
            'readability_score.numeric' => 'مستوى القراءة يجب أن يكون رقماً',
            'readability_score.min' => 'مستوى القراءة لا يمكن أن يكون أقل من 0',
            'readability_score.max' => 'مستوى القراءة لا يمكن أن يتجاوز 10',
            'custom_prompt.string' => 'التعليمات المخصصة يجب أن تكون نصاً',
            'custom_prompt.max' => 'التعليمات المخصصة لا يمكن أن تتعد 2000 حرف',
            'batch_generation.boolean' => 'وضعية التوليد المجمعة مطلوبة',
            'property_ids.required_if' => 'العقارات مطلوبة للوليد المجمعة',
            'property_ids.array' => 'العقارات يجب أن تكون مصفوفة',
            'property_ids.*.exists' => 'أحد العقارات غير موجود',
            'template_id.exists' => 'القالب المحدد غير موجود',
            'variation_count.integer' => 'عدد التباينات مطلوب',
            'variation_count.min' => 'عدد التباينات لا يمكن أن يكون أقل من 1',
            'variation_count.max' => 'عدد التباينات لا يمكن أن يتجاوز 5',
            'property_images.array' => 'صور العقار يجب أن تكون مصفوفة',
            'property_images.*.image.required' => 'الصورة مطلوبة',
            'property_images.*.image.file' => 'الملف يجب أن يكون صورة صالحة',
            'property_images.*.image.image' => 'الملف يجب أن يكون من نوع: jpeg, jpg, png, gif',
            'property_images.*.image.max' => 'حجم الملف لا يمكن أن يتجاوز 10 ميجابايت',
            'property_images.*.primary.boolean' => 'تحديد الصورة الأساسية مطلوب',
            'property_images.*.description.string' => 'وصف الصورة يجب أن يكون نصاً',
            'property_images.*.description.max' => 'وصف الصورة لا يمكن أن يتجاوز 200 حرف',
            'property_images.*.angle.string' => 'زاوية الصورة مطلوبة',
            'property_images.*.angle.max' => 'زاوية الصورة لا يمكن أن يتجاوز 50 حرف',
            'property_images.*.room_type.string' => 'نوع الغرفة مطلوب',
            'property_images.*.room_type.max' => 'نوع الغرفة لا يمكن أن يتجاوز 50 حرف',
            'generation_model.string' => 'نموذج التوليد مطلوب',
            'generation_model.max' => 'نموذج التوليد لا يمكن أن يتجاوز 50 حرف',
            'temperature.numeric' => 'درجة الحرارة يجب أن تكون رقماً',
            'temperature.min' => 'درجة الحرارة لا يمكن أن تكون أقل من 0.1',
            'temperature.max' => 'درجة الحرارة لا يمكن أن تتجاوز 2.0',
            'max_tokens.integer' => 'الحد الأقصى للرموز مطلوب',
            'max_tokens.min' => 'الحد الأقصى للرموز لا يمكن أن يكون أقل من 100',
            'max_tokens.max' => 'الحد الأقصى للرموز لا يمكن أن يتجاوز 4000',
            'use_custom_prompt.boolean' => 'استخدام تعليمات مخصصة مطلوب',
            'reference_descriptions.array' => 'الأوصاف المرجعية يجب أن تكون مصفوفة',
            'reference_descriptions.*.description.required' => 'الوصف المرجعي مطلوب',
            'reference_descriptions.*.description.string' => 'الوصف المرجعي يجب أن يكون نصاً',
            'reference_descriptions.*.description.max' => 'الوصف المرجعي لا يمكن أن يتجاوز 500 حرف',
            'reference_descriptions.*.url.url' => 'الرابط المرجعي يجب أن يكون رابطاً صالححاً',
            'reference_descriptions.*.url.max' => 'الرابط المرجعي لا يمكن أن يتجاوز 500 حرف',
            'avoid_words.array' => 'الكلمات الممنوعة يجب أن تكون مصفوفة',
            'avoid_words.*.word.required' => 'الكلمة الممنوعة مطلوبة',
            'avoid_words.*.word.string' => 'الكلمة الممنوعة يجب أن تكون نصاً',
            'avoid_words.*.word.max' => 'الكلمة الممنوعة لا يمكن أن تتعد 100 حرف',
            'focus_areas.array' => 'مناطق التركيز يجب أن تكون مصفوفة',
            'focus_areas.*.area.required' => 'منطقة التركيز مطلوبة',
            'focus_areas.*.area.string' => 'منطقة التركيز يجب أن تكون نصاً',
            'focus_areas.*.area.max' => 'منطقة التركيز لا يمكن أن تتعد 200 حرف',
            'focus_areas.*.priority.integer' => 'أولوية المنطقة مطلوبة',
            'focus_areas.*.priority.min' => 'أولوية المنطقة لا يمكن أن تكون أقل من 1',
            'focus_areas.*.priority.max' => 'أولوية المنطقة لا يمكن أن تتعد 10',
            'test_instructions.string' => 'تعليمات الاختبار مطلوبة',
            'test_instructions.max' => 'تعليمات الاختبار لا يمكن أن تتعد 1000 حرف',
        ];
    }

    /**
     * Get custom attribute names for validation errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return [
            'property_id' => 'العقار',
            'description_type' => 'نوع الوصف',
            'language' => 'اللغة',
            'tone' => 'نبرة الوصف',
            'target_audience' => 'الجمهور المستهدف',
            'property_features' => 'ميزات العقار',
            'property_features.feature' => 'الميزة',
            'property_features.highlight' => 'تمييز الميزة',
            'property_features.description' => 'وصف الميزة',
            'selling_points' => 'نقاط البيع',
            'selling_points.point' => 'نقطة البيع',
            'selling_points.emphasis' => 'مستوى التركيز',
            'call_to_action' => 'دعوة اتخاذ الإجراء',
            'seo_keywords' => 'كلمات SEO',
            'seo_keywords.keyword' => 'الكلمة المفتاحية',
            'seo_keywords.importance' => 'أهمية الكلمة',
            'property_type' => 'نوع العقار',
            'property_size' => 'مساحة العقار',
            'property_condition' => 'حالة العقار',
            'location_benefits' => 'مزايا الموقع',
            'location_benefits.benefit' => 'الميزة',
            'location_benefits.benefit' => 'وصف الميزة',
            'amenities' => 'المرافق',
            'amenities.amenity' => 'المرفق',
            'amenities.available' => 'توفر',
            'amenities.description' => 'وصف المرفق',
            'nearby_attractions' => 'المعالم القريبة',
            'nearby_attractions.attraction' => 'المعلم القريب',
            'nearby_attractions.distance' => 'المسافة',
            'nearby_attractions.description' => 'وصف المعلم القريب',
            'style_preferences' => 'تفضيلات النمط',
            'style_preferences.style' => 'النمط',
            'style_preferences.color_scheme' => 'خط الألوان',
            'style_preferences.furniture_style' => 'نمط الأثاث',
            'content_length' => 'طول المحتوى',
            'quality_level' => 'مستوى الجودة',
            'engagement_prediction' => 'توقع التفاعل',
            'target_word_count' => 'عدد الكلمات المستهدف',
            'readability_score' => 'مستوى القراءة',
            'custom_instructions' => 'التعليمات المخصصة',
            'reference_descriptions' => 'الأوصاف المرجعية',
            'reference_descriptions.description' => 'الوصف المرجعي',
            'reference_descriptions.url' => 'الرابط المرجعي',
            'avoid_words' => 'الكلمات الممنوعة',
            'avoid_words.word' => 'الكلمة الممنوعة',
            'focus_areas' => 'مناطق التركيز',
            'focus_areas.area' => 'منطقة التركيز',
            'focus_areas.priority' => 'أولوية المنطقة',
            'property_images' => 'صور العقار',
            'property_images.image' => 'الصورة',
            'property_images.primary' => 'الصورة الأساسية',
            'property_images.description' => 'وصف الصورة',
            'property_images.angle' => 'زاوية الصورة',
            'property_images.room_type' => 'نوع الغرفة',
            'generation_model' => 'نموذج التوليد',
            'temperature' => 'درجة الحرارة',
            'max_tokens' => 'الحد الأقصى للرموز',
            'use_custom_prompt' => 'استخدام تعليمات مخصصة',
            'custom_prompt' => 'التعليمات المخصصة',
            'batch_generation' => 'وضعية التوليد المجمعة',
            'property_ids' => 'العقارات',
            'template_id' => 'القالب',
            'variation_count' => 'عدد التباينات',
            'a_b_testing' => 'اختبار أ/ب',
            'test_instructions' => 'تعليمات الاختبار',
        ];
    }
}
