<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class RequestQuoteRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'insurance_provider_id' => 'required|exists:insurance_providers,id',
            'property_id' => 'required|exists:properties,id',
            'title' => 'required|string|max:255',
            'title_ar' => 'nullable|string|max:255',
            'description' => 'nullable|string|max:2000',
            'description_ar' => 'nullable|string|max:2000',
            'coverage_type' => 'required|in:property,liability,comprehensive,fire,flood,earthquake,theft,tenant,landlord,builder_risk,other',
            'coverage_amount' => 'required|numeric|min:0',
            'deductible' => 'nullable|numeric|min:0',
            'premium_amount' => 'nullable|numeric|min:0',
            'payment_frequency' => 'nullable|in:monthly,quarterly,semi_annually,annually',
            'payment_method' => 'nullable|in:cash,bank_transfer,check,credit_card,online,auto_debit',
            'coverage_start_date' => 'required|date|after_or_equal:today',
            'coverage_end_date' => 'required|date|after:coverage_start_date',
            'special_requirements' => 'nullable|array',
            'special_requirements.*' => 'string|max:500',
            'risk_factors' => 'nullable|array',
            'risk_factors.*' => 'string|max:255',
            'property_details' => 'nullable|array',
            'property_details.square_footage' => 'nullable|numeric|min:0',
            'property_details.year_built' => 'nullable|integer|min:1900|max:' . (date('Y') + 1),
            'property_details.construction_type' => 'nullable|string|max:255',
            'property_details.roof_type' => 'nullable|string|max:255',
            'property_details.foundation_type' => 'nullable|string|max:255',
            'property_details.wall_material' => 'nullable|string|max:255',
            'property_details.flooring' => 'nullable|string|max:255',
            'property_details.electrical_system' => 'nullable|string|max:255',
            'property_details.plumbing_system' => 'nullable|string|max:255',
            'property_details.hvac_system' => 'nullable|string|max:255',
            'property_details.security_system' => 'nullable|string|max:255',
            'property_details.fire_safety' => 'nullable|string|max:255',
            'property_details.location_risk' => 'nullable|in:low,medium,high,very_high',
            'property_details.weather_risk' => 'nullable|in:low,medium,high,very_high',
            'property_details.crime_rate' => 'nullable|in:low,medium,high,very_high',
            'property_details.natural_disaster_risk' => 'nullable|in:low,medium,high,very_high',
            'property_details.flood_risk' => 'nullable|in:low,medium,high,very_high',
            'property_details.earthquake_risk' => 'nullable|in:low,medium,high,very_high',
            'occupancy_type' => 'nullable|in:residential,commercial,industrial,mixed',
            'occupancy_details' => 'nullable|array',
            'occupancy_details.residents_count' => 'nullable|integer|min:0',
            'occupancy_details.employees_count' => 'nullable|integer|min:0',
            'occupancy_details.business_type' => 'nullable|string|max:255',
            'occupancy_details.industry_type' => 'nullable|string|max:255',
            'occupancy_details.annual_revenue' => 'nullable|numeric|min:0',
            'previous_claims' => 'nullable|boolean',
            'previous_claims_count' => 'nullable|required_if:previous_claims,true|integer|min:0',
            'previous_claims_details' => 'nullable|string|max:1000',
            'previous_claims_amount' => 'nullable|required_if:previous_claims,true|numeric|min:0',
            'insurance_history' => 'nullable|array',
            'insurance_history.*.provider' => 'required|string|max:255',
            'insurance_history.*.policy_type' => 'required|string|max:255',
            'insurance_history.*.coverage_amount' => 'required|numeric|min:0',
            'insurance_history.*.premium_amount' => 'required|numeric|min:0',
            'insurance_history.*.start_date' => 'required|date',
            'insurance_history.*.end_date' => 'required|date',
            'insurance_history.*.claims_count' => 'required|integer|min:0',
            'insurance_history.*.claims_amount' => 'required|numeric|min:0',
            'insurance_history.*.status' => 'required|string|max:255',
            'desired_coverage' => 'nullable|array',
            'desired_coverage.*.type' => 'required|string|max:255',
            'desired_coverage.*.amount' => 'required|numeric|min:0',
            'desired_coverage.*.priority' => 'required|in:low,medium,high,essential',
            'budget_constraints' => 'nullable|array',
            'budget_constraints.max_premium' => 'required|numeric|min:0',
            'budget_constraints.max_deductible' => 'nullable|numeric|min:0',
            'budget_constraints.payment_frequency' => 'nullable|in:monthly,quarterly,semi_annually,annually',
            'special_conditions' => 'nullable|array',
            'special_conditions.*' => 'string|max:500',
            'exclusions' => 'nullable|array',
            'exclusions.*' => 'string|max:500',
            'additional_benefits' => 'nullable|array',
            'additional_benefits.*' => 'string|max:255',
            'additional_benefits.*.description' => 'nullable|string|max:500',
            'additional_benefits.*.value' => 'nullable|numeric|min:0',
            'contact_preferences' => 'nullable|array',
            'contact_preferences.phone' => 'boolean',
            'contact_preferences.email' => 'boolean',
            'contact_preferences.sms' => 'boolean',
            'contact_preferences.whatsapp' => 'boolean',
            'contact_preferences.mail' => 'boolean',
            'contact_preferences.in_person' => 'boolean',
            'preferred_providers' => 'nullable|array',
            'preferred_providers.*' => 'exists:insurance_providers,id',
            'preferred_providers.*.priority' => 'nullable|in:low,medium,high',
            'preferred_providers.*.reason' => 'nullable|string|max:255',
            'comparison_quotes' => 'nullable|array',
            'comparison_quotes.*.provider_id' => 'required|exists:insurance_providers,id',
            'comparison_quotes.*.premium_amount' => 'required|numeric|min:0',
            'comparison_quotes.*.coverage_amount' => 'required|numeric|min:0',
            'comparison_quotes.*.deductible' => 'nullable|numeric|min:0',
            'comparison_quotes.*.rating' => 'nullable|numeric|min:0|max:5',
            'comparison_quotes.*.notes' => 'nullable|string|max:500',
            'documents' => 'nullable|array',
            'documents.*' => 'file|mimes:pdf,doc,docx,jpg,jpeg,png|max:5120',
            'documents.*.type' => 'required|string|max:255',
            'documents.*.description' => 'nullable|string|max:500',
            'photos' => 'nullable|array',
            'photos.*' => 'image|mimes:jpg,jpeg,png|max:2048',
            'photos.*.type' => 'required|string|max:255',
            'photos.*.description' => 'nullable|string|max:500',
            'videos' => 'nullable|array',
            'videos.*' => 'file|mimes:mp4,avi,mov|max:10240',
            'videos.*.type' => 'required|string|max:255',
            'videos.*.description' => 'nullable|string|max:500',
            'additional_information' => 'nullable|string|max:2000',
            'urgency_level' => 'nullable|in:low,medium,high,urgent',
            'effective_date' => 'nullable|date|after_or_equal:today',
            'request_notes' => 'nullable|string|max:2000',
            'agreement_to_terms' => 'required|boolean',
            'digital_signature' => 'nullable|string|max:255',
            'signature_date' => 'nullable|date',
            'reference_number' => 'nullable|string|max:255',
            'referral_source' => 'nullable|string|max:255',
            'agent_name' => 'nullable|string|max:255',
            'agent_contact' => 'nullable|string|max:255',
            'broker_name' => 'nullable|string|max:255',
            'broker_contact' => 'nullable|string|max:255',
            'legal_review_required' => 'boolean',
            'legal_review_notes' => 'nullable|string|max:1000',
            'binding_quote' => 'boolean',
            'quote_validity_days' => 'nullable|integer|min:1|max:365',
            'auto_renewal' => 'boolean',
            'renewal_terms' => 'nullable|string|max:1000',
            'discount_requested' => 'boolean',
            'discount_reason' => 'nullable|string|max:500',
            'special_instructions' => 'nullable|string|max:1000',
        ];
    }

    /**
     * Get custom error messages for validation rules.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'insurance_provider_id.required' => 'حقل شركة التأمين مطلوب',
            'insurance_provider_id.exists' => 'شركة التأمين المحددة غير موجودة',
            'property_id.required' => 'حقل العقار مطلوب',
            'property_id.exists' => 'العقار المحدد غير موجود',
            'title.required' => 'حقل العنوان مطلوب',
            'title.max' => 'العنوان يجب ألا يزيد عن 255 حرف',
            'title_ar.max' => 'العنوان بالعربية يجب ألا يزيد عن 255 حرف',
            'description.max' => 'الوصف يجب ألا يزيد عن 2000 حرف',
            'description_ar.max' => 'الوصف بالعربية يجب ألا يزيد عن 2000 حرف',
            'coverage_type.required' => 'حقل نوع التغطية مطلوب',
            'coverage_type.in' => 'نوع التغطية غير صالح',
            'coverage_amount.required' => 'حقل مبلغ التغطية مطلوب',
            'coverage_amount.numeric' => 'مبلغ التغطية يجب أن يكون رقم',
            'coverage_amount.min' => 'مبلغ التغطية يجب أن يكون 0 أو أكثر',
            'deductible.numeric' => 'الخصم يجب أن يكون رقم',
            'deductible.min' => 'الخصم يجب أن يكون 0 أو أكثر',
            'premium_amount.numeric' => 'القسط يجب أن يكون رقم',
            'premium_amount.min' => 'القسط يجب أن يكون 0 أو أكثر',
            'payment_frequency.in' => 'تكرار الدفع غير صالح',
            'payment_method.in' => 'طريقة الدفع غير صالحة',
            'coverage_start_date.required' => 'حقل تاريخ بدء التغطية مطلوب',
            'coverage_start_date.after_or_equal' => 'تاريخ بدء التغطية يجب أن يكون اليوم أو بعد',
            'coverage_end_date.required' => 'حقل تاريخ انتهاء التغطية مطلوب',
            'coverage_end_date.after' => 'تاريخ انتهاء التغطية يجب أن يكون بعد تاريخ البدء',
            'special_requirements.array' => 'المتطلبات الخاصة يجب أن تكون مصفوفة',
            'special_requirements.*.max' => 'المطلب الخاص يجب ألا يزيد عن 500 حرف',
            'risk_factors.array' => 'عوامل الخطر يجب أن تكون مصفوفة',
            'risk_factors.*.max' => 'عامل الخطر يجب ألا يزيد عن 255 حرف',
            'property_details.array' => 'تفاصيل العقار يجب أن تكون مصفوفة',
            'property_details.square_footage.numeric' => 'المساحة يجب أن تكون رقم',
            'property_details.square_footage.min' => 'المساحة يجب أن تكون 0 أو أكثر',
            'property_details.year_built.integer' => 'سنة البناء يجب أن تكون رقم صحيح',
            'property_details.year_built.min' => 'سنة البناء يجب أن تكون ' . (date('Y') - 1) . ' أو أكثر',
            'property_details.year_built.max' => 'سنة البناء يجب أن تكون ' . (date('Y') + 1) . ' أو أقل',
            'property_details.construction_type.max' => 'نوع البناء يجب ألا يزيد عن 255 حرف',
            'property_details.roof_type.max' => 'نوع السقف يجب ألا يزيد عن 255 حرف',
            'property_details.foundation_type.max' => 'نوع الأساس يجب ألا يزيد عن 255 حرف',
            'property_details.wall_material.max' => 'نوع الجدران يجب ألا يزيد عن 255 حرف',
            'property_details.flooring.max' => 'نوع الأرضية يجب ألا يزيد عن 255 حرف',
            'property_details.electrical_system.max' => 'نظام الكهرباء يجب ألا يزيد عن 255 حرف',
            'property_details.plumbing_system.max' => 'نظام السباكة يجب ألا يزيد عن 255 حرف',
            'property_details.hvac_system.max' => 'نظام التكييف يجب ألا يزيد عن 255 حرف',
            'property_details.security_system.max' => 'نظام الأمان يجب ألا يزيد عن 255 حرف',
            'property_details.fire_safety.max' => 'سلامة الحريق يجب ألا يزيد عن 255 حرف',
            'property_details.location_risk.in' => 'مخاطر الموقع غير صالح',
            'property_details.weather_risk.in' => 'مخاطر الطقس غير صالح',
            'property_details.crime_rate.in' => 'معدل الجريمة غير صالح',
            'property_details.natural_disaster_risk.in' => 'مخاطر الكوارث الطبيعية غير صالح',
            'property_details.flood_risk.in' => 'مخاطر الفيضانات غير صالح',
            'property_details.earthquake_risk.in' => 'مخاطر الزلازل غير صالح',
            'occupancy_type.in' => 'نوع الإشغال غير صالح',
            'occupancy_details.array' => 'تفاصيل الإشغال يجب أن تكون مصفوفة',
            'occupancy_details.residents_count.integer' => 'عدد السكان يجب أن يكون رقم صحيح',
            'occupancy_details.residents_count.min' => 'عدد السكان يجب أن يكون 0 أو أكثر',
            'occupancy_details.employees_count.integer' => 'عدد الموظفين يجب أن يكون رقم صحيح',
            'occupancy_details.employees_count.min' => 'عدد الموظفين يجب أن يكون 0 أو أكثر',
            'occupancy_details.business_type.max' => 'نوع العمل يجب ألا يزيد عن 255 حرف',
            'occupancy_details.industry_type.max' => 'نوع الصناعة يجب ألا يزيد عن 255 حرف',
            'occupancy_details.annual_revenue.numeric' => 'الإيراد السنوي يجب أن يكون رقم',
            'occupancy_details.annual_revenue.min' => 'الإيراد السنوي يجب أن يكون 0 أو أكثر',
            'previous_claims.boolean' => 'المطالبات السابقة يجب أن تكون true أو false',
            'previous_claims_count.required_if' => 'عدد المطالبات السابقة مطلوب عند وجود مطالبات سابقة',
            'previous_claims_count.integer' => 'عدد المطالبات السابقة يجب أن يكون رقم صحيح',
            'previous_claims_count.min' => 'عدد المطالبات السابقة يجب أن يكون 0 أو أكثر',
            'previous_claims_details.max' => 'تفاصيل المطالبات السابقة يجب ألا يزيد عن 1000 حرف',
            'previous_claims_amount.required_if' => 'مبلغ المطالبات السابقة مطلوب عند وجود مطالبات سابقة',
            'previous_claims_amount.numeric' => 'مبلغ المطالبات السابقة يجب أن يكون رقم',
            'previous_claims_amount.min' => 'مبلغ المطالبات السابقة يجب أن يكون 0 أو أكثر',
            'insurance_history.array' => 'سجل التأمين يجب أن يكون مصفوفة',
            'insurance_history.*.provider.required' => 'اسم شركة التأمين مطلوب',
            'insurance_history.*.provider.max' => 'اسم شركة التأمين يجب ألا يزيد عن 255 حرف',
            'insurance_history.*.policy_type.required' => 'نوع البوليصة مطلوب',
            'insurance_history.*.policy_type.max' => 'نوع البوليصة يجب ألا يزيد عن 255 حرف',
            'insurance_history.*.coverage_amount.required' => 'مبلغ التغطية مطلوب',
            'insurance_history.*.coverage_amount.numeric' => 'مبلغ التغطية يجب أن يكون رقم',
            'insurance_history.*.coverage_amount.min' => 'مبلغ التغطية يجب أن يكون 0 أو أكثر',
            'insurance_history.*.premium_amount.required' => 'القسط مطلوب',
            'insurance_history.*.premium_amount.numeric' => 'القسط يجب أن يكون رقم',
            'insurance_history.*.premium_amount.min' => 'القسط يجب أن يكون 0 أو أكثر',
            'insurance_history.*.start_date.required' => 'تاريخ البدء مطلوب',
            'insurance_history.*.start_date.date' => 'تاريخ البدء يجب أن يكون تاريخ صالح',
            'insurance_history.*.end_date.required' => 'تاريخ الانتهاء مطلوب',
            'insurance_history.*.end_date.date' => 'تاريخ الانتهاء يجب أن يكون تاريخ صالح',
            'insurance_history.*.claims_count.required' => 'عدد المطالبات مطلوب',
            'insurance_history.*.claims_count.integer' => 'عدد المطالبات يجب أن يكون رقم صحيح',
            'insurance_history.*.claims_count.min' => 'عدد المطالبات يجب أن يكون 0 أو أكثر',
            'insurance_history.*.claims_amount.required' => 'مبلغ المطالبات مطلوب',
            'insurance_history.*.claims_amount.numeric' => 'مبلغ المطالبات يجب أن يكون رقم',
            'insurance_history.*.claims_amount.min' => 'مبلغ المطالبات يجب أن يكون 0 أو أكثر',
            'insurance_history.*.status.required' => 'الحالة مطلوبة',
            'insurance_history.*.status.max' => 'الحالة يجب ألا يزيد عن 255 حرف',
            'desired_coverage.array' => 'التغطية المطلوبة يجب أن تكون مصفوفة',
            'desired_coverage.*.type.required' => 'نوع التغطية مطلوب',
            'desired_coverage.*.type.max' => 'نوع التغطية يجب ألا يزيد عن 255 حرف',
            'desired_coverage.*.amount.required' => 'مبلغ التغطية مطلوب',
            'desired_coverage.*.amount.numeric' => 'مبلغ التغطية يجب أن يكون رقم',
            'desired_coverage.*.amount.min' => 'مبلغ التغطية يجب أن يكون 0 أو أكثر',
            'desired_coverage.*.priority.required' => 'الأولوية مطلوبة',
            'desired_coverage.*.priority.in' => 'الأولوية غير صالحة',
            'budget_constraints.array' => 'قيود الميزانية يجب أن تكون مصفوفة',
            'budget_constraints.max_premium.required' => 'الحد الأقصى للقسط مطلوب',
            'budget_constraints.max_premium.numeric' => 'الحد الأقصى للقسط يجب أن يكون رقم',
            'budget_constraints.max_premium.min' => 'الحد الأقصى للقسط يجب أن يكون 0 أو أكثر',
            'budget_constraints.max_deductible.numeric' => 'الحد الأقصى للخصم يجب أن يكون رقم',
            'budget_constraints.max_deductible.min' => 'الحد الأقصى للخصم يجب أن يكون 0 أو أكثر',
            'budget_constraints.payment_frequency.in' => 'تكرار الدفع غير صالح',
            'special_conditions.array' => 'الشروط الخاصة يجب أن تكون مصفوفة',
            'special_conditions.*.max' => 'الشرط الخاص يجب ألا يزيد عن 500 حرف',
            'exclusions.array' => 'الاستثناءات يجب أن تكون مصفوفة',
            'exclusions.*.max' => 'الاستثناء يجب ألا يزيد عن 500 حرف',
            'additional_benefits.array' => 'المزايا الإضافية يجب أن تكون مصفوفة',
            'additional_benefits.*.type.required' => 'نوع الميزة الإضافية مطلوب',
            'additional_benefits.*.type.max' => 'نوع الميزة الإضافية يجب ألا يزيد عن 255 حرف',
            'additional_benefits.*.description.max' => 'وصف الميزة الإضافية يجب ألا يزيد عن 500 حرف',
            'additional_benefits.*.value.numeric' => 'قيمة الميزة الإضافية يجب أن يكون رقم',
            'additional_benefits.*.value.min' => 'قيمة الميزة الإضافية يجب أن يكون 0 أو أكثر',
            'contact_preferences.array' => 'تفضيلات الاتصال يجب أن تكون مصفوفة',
            'contact_preferences.phone.boolean' => 'تفضيل الاتصال الهاتفي يجب أن يكون true أو false',
            'contact_preferences.email.boolean' => 'تفضيل الاتصال البريدي يجب أن يكون true أو false',
            'contact_preferences.sms.boolean' => 'تفضيل الرسائل النصية يجب أن يكون true أو false',
            'contact_preferences.whatsapp.boolean' => 'تفضيل واتساب يجب أن يكون true أو false',
            'contact_preferences.mail.boolean' => 'تفضيل البريد يجب أن يكون true أو false',
            'contact_preferences.in_person.boolean' => 'تفضيل اللقاء الشخصي يجب أن يكون true أو false',
            'preferred_providers.array' => 'مزود الشركات المفضلة يجب أن تكون مصفوفة',
            'preferred_providers.*.exists' => 'الشركة المفضلة يجب أن تكون موجودة',
            'preferred_providers.*.priority.in' => 'الأولوية المفضلة غير صالحة',
            'preferred_providers.*.reason.max' => 'سبب التفضيل يجب ألا يزيد عن 255 حرف',
            'comparison_quotes.array' => 'عروض المقارنة يجب أن تكون مصفوفة',
            'comparison_quotes.*.provider_id.required' => 'معرف شركة التأمين مطلوب',
            'comparison_quotes.*.provider_id.exists' => 'معرف شركة التأمين يجب أن يكون موجوداً',
            'comparison_quotes.*.premium_amount.required' => 'قسط العرض مطلوب',
            'comparison_quotes.*.premium_amount.numeric' => 'قسط العرض يجب أن يكون رقم',
            'comparison_quotes.*.premium_amount.min' => 'قسط العرض يجب أن يكون 0 أو أكثر',
            'comparison_quotes.*.coverage_amount.required' => 'التغطية العرض مطلوب',
            'comparison_quotes.*.coverage_amount.numeric' => 'التغطية العرض يجب أن يكون رقم',
            'comparison_quotes.*.coverage_amount.min' => 'التغطية العرض يجب أن يكون 0 أو أكثر',
            'comparison_quotes.*.deductible.numeric' => 'خصم العرض يجب أن يكون رقم',
            'comparison_quotes.*.deductible.min' => 'خصم العرض يجب أن يكون 0 أو أكثر',
            'comparison_quotes.*.rating.numeric' => 'تقييم العرض يجب أن يكون رقم',
            'comparison_quotes.*.rating.min' => 'تقييم العرض يجب أن يكون 0 أو أكثر',
            'comparison_quotes.*.rating.max' => 'تقييم العرض يجب أن يكون 5 أو أقل',
            'comparison_quotes.*.notes.max' => 'ملاحظات العرض يجب ألا يزيد عن 500 حرف',
            'documents.array' => 'المستندات يجب أن تكون مصفوفة',
            'documents.*.file' => 'يجب أن يكون المستند ملف',
            'documents.*.mimes' => 'نوع ملف المستند غير مدعوع. الأنواع المدعوعة: pdf, doc, docx, jpg, jpeg, png',
            'documents.*.max' => 'حجم ملف المستند يجب ألا يزيد عن 5 ميجابايت',
            'documents.*.type.required' => 'نوع المستند مطلوب',
            'documents.*.description.max' => 'وصف المستند يجب ألا يزيد عن 500 حرف',
            'photos.array' => 'الصور يجب أن تكون مصفوفة',
            'photos.*.image' => 'يجب أن يكون الملف صورة',
            'photos.*.mimes' => 'نوع الصورة غير مدعوع. الأنواع المدعوعة: jpg, jpeg, png',
            'photos.*.max' => 'حجم الصورة يجب ألا يزيد عن 2 ميجابايت',
            'photos.*.type.required' => 'نوع الصورة مطلوب',
            'photos.*.description.max' => 'وصف الصورة يجب ألا يزيد عن 500 حرف',
            'videos.array' => 'الفيديوهات يجب أن تكون مصفوفة',
            'videos.*.file' => 'يجب أن يكون الملف فيديو',
            'videos.*.mimes' => 'نوع ملف الفيديو غير مدعوع. الأنواع المدعوعة: mp4, avi, mov',
            'videos.*.max' => 'حجم ملف الفيديو يجب ألا يزيد عن 10 ميجابايت',
            'videos.*.type.required' => 'نوع الفيديو مطلوب',
            'videos.*.description.max' => 'وصف الفيديو يجب ألا يزيد عن 500 حرف',
            'additional_information.max' => 'معلومات إضافية يجب ألا تزيد عن 2000 حرف',
            'urgency_level.in' => 'مستوى الطوارئ غير صالح',
            'effective_date.date' => 'تاريخ السريع يجب أن يكون تاريخ صالح',
            'effective_date.after_or_equal' => 'تاريخ السريع يجب أن يكون اليوم أو بعد',
            'request_notes.max' => 'ملاحظات الطلب يجب ألا تزيد عن 2000 حرف',
            'agreement_to_terms.required' => 'الموافقة على الشروط مطلوبة',
            'agreement_to_terms.boolean' => 'الموافقة على الشروط يجب أن تكون true أو false',
            'digital_signature.max' => 'التوقيع الرقمي يجب ألا يزيد عن 255 حرف',
            'signature_date.date' => 'تاريخ التوقيع يجب أن يكون تاريخ صالح',
            'reference_number.max' => 'رقم المرجع يجب ألا يزيد عن 255 حرف',
            'referral_source.max' => 'مصدر الإحالة يجب ألا يزيد عن 255 حرف',
            'agent_name.max' => 'اسم الوكيل يجب ألا يزيد عن 255 حرف',
            'agent_contact.max' => 'بيانات الوكيل يجب ألا يزيد عن 255 حرف',
            'broker_name.max' => 'اسم الوسيط يجب ألا يزيد عن 255 حرف',
            'broker_contact.max' => 'بيانات الوسيط يجب ألا يزيد عن 255 حرف',
            'legal_review_required.boolean' => 'المراجعة القانونية يجب أن تكون true أو false',
            'legal_review_notes.max' => 'ملاحظات المراجعة يجب ألا تزيد عن 1000 حرف',
            'binding_quote.boolean' => 'عرض السعر الملزم يجب أن يكون true أو false',
            'quote_validity_days.integer' => 'صلاحية العرض يجب أن تكون رقم صحيح',
            'quote_validity_days.min' => 'صلاحية العرض يجب أن تكون 1 يوم على الأقل',
            'quote_validity_days.max' => 'صلاحية العرض يجب أن تكون 365 يوم أو أقل',
            'auto_renewal.boolean' => 'التجديد التلقائي يجب أن يكون true أو false',
            'renewal_terms.max' => 'شروط التجديد يجب ألا تزيد عن 1000 حرف',
            'discount_requested.boolean' => 'طلب خصم يجب أن يكون true أو false',
            'discount_reason.max' => 'سبب الخصم يجب ألا يزيد عن 500 حرف',
            'special_instructions.max' => 'تعليمات خاصة يجب ألا تزيد عن 1000 حرف',
        ];
    }
}
