<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class SubmitClaimRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'insurance_policy_id' => 'required|exists:insurance_policies,id',
            'title' => 'required|string|max:255',
            'title_ar' => 'nullable|string|max:255',
            'description' => 'required|string|max:2000',
            'description_ar' => 'nullable|string|max:2000',
            'claim_type' => 'required|in:property_damage,liability,theft,fire,flood,earthquake,water_damage,vandalism,natural_disaster,accident,other',
            'incident_date' => 'required|date|before_or_equal:today',
            'incident_location' => 'nullable|string|max:500',
            'incident_description' => 'nullable|string|max:2000',
            'claimed_amount' => 'required|numeric|min:0',
            'estimated_damage' => 'nullable|numeric|min:0',
            'damage_type' => 'nullable|string|max:255',
            'cause_of_loss' => 'nullable|string|max:500',
            'witnesses' => 'nullable|array',
            'witnesses.*.name' => 'required|string|max:255',
            'witnesses.*.phone' => 'required|string|max:20',
            'witnesses.*.email' => 'nullable|email|max:255',
            'witnesses.*.statement' => 'nullable|string|max:1000',
            'police_report' => 'boolean',
            'police_report_number' => 'nullable|required_if:police_report,true|string|max:255',
            'police_report_date' => 'nullable|required_if:police_report,true|date',
            'emergency_services' => 'boolean',
            'emergency_services_type' => 'nullable|required_if:emergency_services,true|in:police,fire,ambulance,other',
            'emergency_services_response_time' => 'nullable|string|max:255',
            'medical_attention' => 'boolean',
            'medical_attention_type' => 'nullable|required_if:medical_attention,true|string|max:255',
            'medical_attention_hospital' => 'nullable|string|max:255',
            'injuries' => 'nullable|string|max:1000',
            'property_damage' => 'nullable|string|max:1000',
            'other_losses' => 'nullable|string|max:1000',
            'immediate_actions' => 'nullable|string|max:1000',
            'preventive_measures' => 'nullable|string|max:1000',
            'priority' => 'nullable|in:low,medium,high,urgent',
            'assigned_to' => 'nullable|exists:users,id',
            'estimated_settlement_date' => 'nullable|date|after:today',
            'documents' => 'nullable|array',
            'documents.*' => 'file|mimes:pdf,doc,docx,jpg,jpeg,png|max:5120',
            'photos' => 'nullable|array',
            'photos.*' => 'image|mimes:jpg,jpeg,png|max:2048',
            'videos' => 'nullable|array',
            'videos.*' => 'file|mimes:mp4,avi,mov|max:10240',
            'additional_evidence' => 'nullable|string|max:2000',
            'contact_preferences' => 'nullable|array',
            'contact_preferences.phone' => 'boolean',
            'contact_preferences.email' => 'boolean',
            'contact_preferences.sms' => 'boolean',
            'contact_preferences.whatsapp' => 'boolean',
            'notification_frequency' => 'nullable|in:daily,weekly,monthly,never',
            'legal_representation' => 'boolean',
            'lawyer_name' => 'nullable|required_if:legal_representation,true|string|max:255',
            'lawyer_contact' => 'nullable|required_if:legal_representation,true|string|max:255',
            'insurance_adjuster' => 'nullable|string|max:255',
            'insurance_adjuster_contact' => 'nullable|string|max:255',
            'third_party_involved' => 'boolean',
            'third_party_details' => 'nullable|required_if:third_party_involved,true|array',
            'third_party_details.name' => 'required|string|max:255',
            'third_party_details.contact' => 'required|string|max:255',
            'third_party_details.insurance' => 'nullable|string|max:255',
            'third_party_details.policy_number' => 'nullable|string|max:255',
            'temporary_repairs' => 'boolean',
            'temporary_repairs_cost' => 'nullable|required_if:temporary_repairs,true|numeric|min:0',
            'temporary_repairs_description' => 'nullable|string|max:1000',
            'business_interruption' => 'boolean',
            'business_interruption_days' => 'nullable|required_if:business_interruption,true|integer|min:1',
            'business_interruption_income_loss' => 'nullable|required_if:business_interruption,true|numeric|min:0',
            'additional_expenses' => 'nullable|array',
            'additional_expenses.*.type' => 'required|string|max:255',
            'additional_expenses.*.amount' => 'required|numeric|min:0',
            'additional_expenses.*.description' => 'nullable|string|max:500',
            'previous_claims' => 'boolean',
            'previous_claims_count' => 'nullable|required_if:previous_claims,true|integer|min:0',
            'previous_claims_details' => 'nullable|string|max:1000',
            'maintenance_records' => 'nullable|array',
            'maintenance_records.*.date' => 'required|date',
            'maintenance_records.*.description' => 'required|string|max:500',
            'maintenance_records.*.cost' => 'nullable|numeric|min:0',
            'property_condition_before' => 'nullable|string|max:1000',
            'security_measures' => 'nullable|array',
            'security_measures.*.type' => 'required|string|max:255',
            'security_measures.*.description' => 'nullable|string|max:500',
            'security_measures.*.functional' => 'boolean',
            'weather_conditions' => 'nullable|string|max:255',
            'visibility_conditions' => 'nullable|string|max:255',
            'road_conditions' => 'nullable|string|max:255',
            'contributing_factors' => 'nullable|array',
            'contributing_factors.*' => 'string|max:255',
            'mitigation_steps' => 'nullable|array',
            'mitigation_steps.*' => 'string|max:500',
            'expert_witness_needed' => 'boolean',
            'expert_witness_type' => 'nullable|required_if:expert_witness_needed,true|string|max:255',
            'reconstruction_estimates' => 'nullable|array',
            'reconstruction_estimates.*.contractor' => 'required|string|max:255',
            'reconstruction_estimates.*.amount' => 'required|numeric|min:0',
            'reconstruction_estimates.*.timeline' => 'nullable|string|max:255',
            'personal_items_affected' => 'nullable|array',
            'personal_items_affected.*.item' => 'required|string|max:255',
            'personal_items_affected.*.value' => 'required|numeric|min:0',
            'personal_items_affected.*.age' => 'nullable|integer|min:0',
            'personal_items_affected.*.condition' => 'required|in:excellent,good,fair,poor',
            'replacement_cost_vs_repair' => 'nullable|string|max:1000',
            'depreciation_considerations' => 'nullable|string|max:1000',
            'claim_history_notes' => 'nullable|string|max:2000',
            'special_instructions' => 'nullable|string|max:1000',
            'confidential_information' => 'nullable|string|max:2000',
            'agreement_to_terms' => 'required|boolean',
            'digital_signature' => 'nullable|string|max:255',
            'signature_date' => 'nullable|date',
        ];
    }

    /**
     * Get custom error messages for validation rules.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'insurance_policy_id.required' => 'حقل بوليصة التأمين مطلوب',
            'insurance_policy_id.exists' => 'بوليصة التأمين المحددة غير موجودة',
            'title.required' => 'حقل العنوان مطلوب',
            'title.max' => 'العنوان يجب ألا يزيد عن 255 حرف',
            'title_ar.max' => 'العنوان بالعربية يجب ألا يزيد عن 255 حرف',
            'description.required' => 'حقل الوصف مطلوب',
            'description.max' => 'الوصف يجب ألا يزيد عن 2000 حرف',
            'description_ar.max' => 'الوصف بالعربية يجب ألا يزيد عن 2000 حرف',
            'claim_type.required' => 'حقل نوع المطالبة مطلوب',
            'claim_type.in' => 'نوع المطالبة غير صالح',
            'incident_date.required' => 'حقل تاريخ الحادث مطلوب',
            'incident_date.before_or_equal' => 'تاريخ الحادث يجب أن يكون اليوم أو قبل',
            'incident_location.max' => 'موقع الحادث يجب ألا يزيد عن 500 حرف',
            'incident_description.max' => 'وصف الحادث يجب ألا يزيد عن 2000 حرف',
            'claimed_amount.required' => 'حقل المبلغ المطالب به مطلوب',
            'claimed_amount.numeric' => 'المبلغ المطالب به يجب أن يكون رقم',
            'claimed_amount.min' => 'المبلغ المطالب به يجب أن يكون 0 أو أكثر',
            'estimated_damage.numeric' => 'تقدير الأضرار يجب أن يكون رقم',
            'estimated_damage.min' => 'تقدير الأضرار يجب أن يكون 0 أو أكثر',
            'damage_type.max' => 'نوع الضرر يجب ألا يزيد عن 255 حرف',
            'cause_of_loss.max' => 'سبب الخسارة يجب ألا يزيد عن 500 حرف',
            'witnesses.array' => 'الشهود يجب أن يكونوا مصفوفة',
            'witnesses.*.name.required' => 'اسم الشاهد مطلوب',
            'witnesses.*.name.max' => 'اسم الشاهد يجب ألا يزيد عن 255 حرف',
            'witnesses.*.phone.required' => 'هاتف الشاهد مطلوب',
            'witnesses.*.phone.max' => 'هاتف الشاهد يجب ألا يزيد عن 20 حرف',
            'witnesses.*.email.email' => 'بريد الشاهد الإلكتروني يجب أن يكون صالح',
            'witnesses.*.email.max' => 'بريد الشاهد الإلكتروني يجب ألا يزيد عن 255 حرف',
            'witnesses.*.statement.max' => 'بيان الشاهد يجب ألا يزيد عن 1000 حرف',
            'police_report.boolean' => 'تقرير الشرطة يجب أن يكون true أو false',
            'police_report_number.required_if' => 'رقم تقرير الشرطة مطلوب عند وجود تقرير شرطة',
            'police_report_number.max' => 'رقم تقرير الشرطة يجب ألا يزيد عن 255 حرف',
            'police_report_date.required_if' => 'تاريخ تقرير الشرطة مطلوب عند وجود تقرير شرطة',
            'police_report_date.date' => 'تاريخ تقرير الشرطة يجب أن يكون تاريخ صالح',
            'emergency_services.boolean' => 'الخدمات الطارئة يجب أن تكون true أو false',
            'emergency_services_type.required_if' => 'نوع الخدمات الطارئة مطلوب عند وجود خدمات طارئة',
            'emergency_services_type.in' => 'نوع الخدمات الطارئة غير صالح',
            'emergency_services_response_time.max' => 'وقت استجابة الخدمات الطارئة يجب ألا يزيد عن 255 حرف',
            'medical_attention.boolean' => 'العناية الطبية يجب أن تكون true أو false',
            'medical_attention_type.required_if' => 'نوع العناية الطبية مطلوب عند وجود عناية طبية',
            'medical_attention_type.max' => 'نوع العناية الطبية يجب ألا يزيد عن 255 حرف',
            'medical_attention_hospital.max' => 'المستشفى يجب ألا يزيد عن 255 حرف',
            'injuries.max' => 'الإصابات يجب ألا تزيد عن 1000 حرف',
            'property_damage.max' => 'الأضرار العقارية يجب ألا تزيد عن 1000 حرف',
            'other_losses.max' => 'الخسائر الأخرى يجب ألا تزيد عن 1000 حرف',
            'immediate_actions.max' => 'الإجراءات الفورية يجب ألا تزيد عن 1000 حرف',
            'preventive_measures.max' => 'التدابير الوقائية يجب ألا تزيد عن 1000 حرف',
            'priority.in' => 'الأولوية غير صالحة',
            'assigned_to.exists' => 'الموظف المحدد غير موجود',
            'estimated_settlement_date.date' => 'تاريخ التقدير المقدر يجب أن يكون تاريخ صالح',
            'estimated_settlement_date.after' => 'تاريخ التقدير المقدر يجب أن يكون بعد اليوم',
            'documents.array' => 'المستندات يجب أن تكون مصفوفة',
            'documents.*.file' => 'يجب أن يكون المستند ملف',
            'documents.*.mimes' => 'نوع ملف المستند غير مدعوع. الأنواع المدعوعة: pdf, doc, docx, jpg, jpeg, png',
            'documents.*.max' => 'حجم ملف المستند يجب ألا يزيد عن 5 ميجابايت',
            'photos.array' => 'الصور يجب أن تكون مصفوفة',
            'photos.*.image' => 'يجب أن يكون الملف صورة',
            'photos.*.mimes' => 'نوع الصورة غير مدعوع. الأنواع المدعوعة: jpg, jpeg, png',
            'photos.*.max' => 'حجم الصورة يجب ألا يزيد عن 2 ميجابايت',
            'videos.array' => 'الفيديوهات يجب أن تكون مصفوفة',
            'videos.*.file' => 'يجب أن يكون الملف فيديو',
            'videos.*.mimes' => 'نوع ملف الفيديو غير مدعوع. الأنواع المدعوعة: mp4, avi, mov',
            'videos.*.max' => 'حجم ملف الفيديو يجب ألا يزيد عن 10 ميجابايت',
            'additional_evidence.max' => 'الأدلة الإضافية يجب ألا تزيد عن 2000 حرف',
            'contact_preferences.array' => 'تفضيلات الاتصال يجب أن تكون مصفوفة',
            'contact_preferences.phone.boolean' => 'تفضيل الاتصال الهاتفي يجب أن يكون true أو false',
            'contact_preferences.email.boolean' => 'تفضيل الاتصال البريدي يجب أن يكون true أو false',
            'contact_preferences.sms.boolean' => 'تفضيل الاتصال بالرسائل يجب أن يكون true أو false',
            'contact_preferences.whatsapp.boolean' => 'تفضيل الاتصال بواتساب يجب أن يكون true أو false',
            'notification_frequency.in' => 'تكرار الإشعارات غير صالح',
            'legal_representation.boolean' => 'التمثيل القانوني يجب أن يكون true أو false',
            'lawyer_name.required_if' => 'اسم المحامي مطلوب عند وجود تمثيل قانوني',
            'lawyer_name.max' => 'اسم المحامي يجب ألا يزيد عن 255 حرف',
            'lawyer_contact.required_if' => 'بيانات المحامي مطلوبة عند وجود تمثيل قانوني',
            'lawyer_contact.max' => 'بيانات المحامي يجب ألا تزيد عن 255 حرف',
            'insurance_adjuster.max' => 'خبير التأمين يجب ألا يزيد عن 255 حرف',
            'insurance_adjuster_contact.max' => 'بيانات خبير التأمين يجب ألا تزيد عن 255 حرف',
            'third_party_involved.boolean' => 'الأطراف الثالثة يجب أن تكون true أو false',
            'third_party_details.required_if' => 'تفاصيل الأطراف الثالثة مطلوبة عند وجود أطراف ثالثة',
            'third_party_details.array' => 'تفاصيل الأطراف الثالثة يجب أن تكون مصفوفة',
            'third_party_details.name.required' => 'اسم الطرف الثالث مطلوب',
            'third_party_details.name.max' => 'اسم الطرف الثالث يجب ألا يزيد عن 255 حرف',
            'third_party_details.contact.required' => 'بيانات الطرف الثالث مطلوبة',
            'third_party_details.contact.max' => 'بيانات الطرف الثالث يجب ألا تزيد عن 255 حرف',
            'third_party_details.insurance.max' => 'تأمين الطرف الثالث يجب ألا يزيد عن 255 حرف',
            'third_party_details.policy_number.max' => 'رقم بوليصة الطرف الثالث يجب ألا يزيد عن 255 حرف',
            'temporary_repairs.boolean' => 'الإصلاحات المؤقتة يجب أن تكون true أو false',
            'temporary_repairs_cost.required_if' => 'تكلفة الإصلاحات المؤقتة مطلوبة عند وجود إصلاحات مؤقتة',
            'temporary_repairs_cost.numeric' => 'تكلفة الإصلاحات المؤقتة يجب أن تكون رقم',
            'temporary_repairs_cost.min' => 'تكلفة الإصلاحات المؤقتة يجب أن تكون 0 أو أكثر',
            'temporary_repairs_description.max' => 'وصف الإصلاحات المؤقتة يجب ألا يزيد عن 1000 حرف',
            'business_interruption.boolean' => 'انقطاع الأعمال يجب أن يكون true أو false',
            'business_interruption_days.required_if' => 'أيام انقطاع الأعمال مطلوبة عند وجود انقطاع أعمال',
            'business_interruption_days.integer' => 'أيام انقطاع الأعمال يجب أن تكون رقم صحيح',
            'business_interruption_days.min' => 'أيام انقطاع الأعمال يجب أن تكون 1 أو أكثر',
            'business_interruption_income_loss.required_if' => 'خسارة الدخل من انقطاع الأعمال مطلوبة عند وجود انقطاع أعمال',
            'business_interruption_income_loss.numeric' => 'خسارة الدخل يجب أن تكون رقم',
            'business_interruption_income_loss.min' => 'خسارة الدخل يجب أن تكون 0 أو أكثر',
            'additional_expenses.array' => 'النفقات الإضافية يجب أن تكون مصفوفة',
            'additional_expenses.*.type.required' => 'نوع النفقة الإضافية مطلوب',
            'additional_expenses.*.type.max' => 'نوع النفقة الإضافية يجب ألا يزيد عن 255 حرف',
            'additional_expenses.*.amount.required' => 'مبلغ النفقة الإضافية مطلوب',
            'additional_expenses.*.amount.numeric' => 'مبلغ النفقة الإضافية يجب أن يكون رقم',
            'additional_expenses.*.amount.min' => 'مبلغ النفقة الإضافية يجب أن يكون 0 أو أكثر',
            'additional_expenses.*.description.max' => 'وصف النفقة الإضافية يجب ألا يزيد عن 500 حرف',
            'previous_claims.boolean' => 'المطالبات السابقة يجب أن تكون true أو false',
            'previous_claims_count.required_if' => 'عدد المطالبات السابقة مطلوب عند وجود مطالبات سابقة',
            'previous_claims_count.integer' => 'عدد المطالبات السابقة يجب أن يكون رقم صحيح',
            'previous_claims_count.min' => 'عدد المطالبات السابقة يجب أن يكون 0 أو أكثر',
            'previous_claims_details.max' => 'تفاصيل المطالبات السابقة يجب ألا تزيد عن 1000 حرف',
            'maintenance_records.array' => 'سجلات الصيانة يجب أن تكون مصفوفة',
            'maintenance_records.*.date.required' => 'تاريخ سجل الصيانة مطلوب',
            'maintenance_records.*.date.date' => 'تاريخ سجل الصيانة يجب أن يكون تاريخ صالح',
            'maintenance_records.*.description.required' => 'وصف سجل الصيانة مطلوب',
            'maintenance_records.*.description.max' => 'وصف سجل الصيانة يجب ألا يزيد عن 500 حرف',
            'maintenance_records.*.cost.numeric' => 'تكلفة سجل الصيانة يجب أن تكون رقم',
            'maintenance_records.*.cost.min' => 'تكلفة سجل الصيانة يجب أن تكون 0 أو أكثر',
            'property_condition_before.max' => 'حالة العقار قبل الحادث يجب ألا تزيد عن 1000 حرف',
            'security_measures.array' => 'التدابير الأمنية يجب أن تكون مصفوفة',
            'security_measures.*.type.required' => 'نوع التدبير الأمني مطلوب',
            'security_measures.*.type.max' => 'نوع التدبير الأمني يجب ألا يزيد عن 255 حرف',
            'security_measures.*.description.max' => 'وصف التدبير الأمني يجب ألا يزيد عن 500 حرف',
            'security_measures.*.functional.boolean' => 'حالة تشغيل التدبير الأمني يجب أن تكون true أو false',
            'weather_conditions.max' => 'الظروف الجوية يجب ألا تزيد عن 255 حرف',
            'visibility_conditions.max' => 'ظروف الرؤية يجب ألا تزيد عن 255 حرف',
            'road_conditions.max' => 'حالة الطريق يجب ألا تزيد عن 255 حرف',
            'contributing_factors.array' => 'العوامل المساهمة يجب أن تكون مصفوفة',
            'contributing_factors.*.max' => 'العامل المساهم يجب ألا يزيد عن 255 حرف',
            'mitigation_steps.array' => 'خطوات التخفيف يجب أن تكون مصفوفة',
            'mitigation_steps.*.max' => 'خطوة التخفيف يجب ألا تزيد عن 500 حرف',
            'expert_witness_needed.boolean' => 'الحاجة لخبير شهادة يجب أن تكون true أو false',
            'expert_witness_type.required_if' => 'نوع الخبير الشاهد مطلوب عند الحاجة لخبير شهادة',
            'expert_witness_type.max' => 'نوع الخبير الشاهد يجب ألا يزيد عن 255 حرف',
            'reconstruction_estimates.array' => 'تقديرات إعادة البناء يجب أن تكون مصفوفة',
            'reconstruction_estimates.*.contractor.required' => 'اسم المقاول مطلوب',
            'reconstruction_estimates.*.contractor.max' => 'اسم المقاول يجب ألا يزيد عن 255 حرف',
            'reconstruction_estimates.*.amount.required' => 'مبلغ التقدير مطلوب',
            'reconstruction_estimates.*.amount.numeric' => 'مبلغ التقدير يجب أن يكون رقم',
            'reconstruction_estimates.*.amount.min' => 'مبلغ التقدير يجب أن يكون 0 أو أكثر',
            'reconstruction_estimates.*.timeline.max' => 'الجدول الزمني يجب ألا يزيد عن 255 حرف',
            'personal_items_affected.array' => 'الأغراض الشخصية المتأثرة يجب أن تكون مصفوفة',
            'personal_items_affected.*.item.required' => 'اسم الغرض الشخصي مطلوب',
            'personal_items_affected.*.item.max' => 'اسم الغرض الشخصي يجب ألا يزيد عن 255 حرف',
            'personal_items_affected.*.value.required' => 'قيمة الغرض الشخصي مطلوبة',
            'personal_items_affected.*.value.numeric' => 'قيمة الغرض الشخصي يجب أن تكون رقم',
            'personal_items_affected.*.value.min' => 'قيمة الغرض الشخصي يجب أن تكون 0 أو أكثر',
            'personal_items_affected.*.age.integer' => 'عمر الغرض الشخصي يجب أن يكون رقم صحيح',
            'personal_items_affected.*.age.min' => 'عمر الغرض الشخصي يجب أن يكون 0 أو أكثر',
            'personal_items_affected.*.condition.required' => 'حالة الغرض الشخصي مطلوبة',
            'personal_items_affected.*.condition.in' => 'حالة الغرض الشخصي غير صالحة',
            'replacement_cost_vs_repair.max' => 'تكلفة الاستبدال مقابل الإصلاح يجب ألا تزيد عن 1000 حرف',
            'depreciation_considerations.max' => 'اعتبارات الاستهلاك يجب ألا تزيد عن 1000 حرف',
            'claim_history_notes.max' => 'ملاحظات سجل المطالبات يجب ألا تزيد عن 2000 حرف',
            'special_instructions.max' => 'تعليمات خاصة يجب ألا تزيد عن 1000 حرف',
            'confidential_information.max' => 'معلومات سرية يجب ألا تزيد عن 2000 حرف',
            'agreement_to_terms.required' => 'الموافقة على الشروط مطلوبة',
            'agreement_to_terms.boolean' => 'الموافقة على الشروط يجب أن تكون true أو false',
            'digital_signature.max' => 'التوقيع الرقمي يجب ألا يزيد عن 255 حرف',
            'signature_date.date' => 'تاريخ التوقيع يجب أن يكون تاريخ صالح',
        ];
    }
}
