<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::table('agencies', function (Blueprint $table) {
            // Add deleted_at column for soft deletes if it doesn't exist
            if (!Schema::hasColumn('agencies', 'deleted_at')) {
                $table->timestamp('deleted_at')->nullable()->after('updated_at');
            }
            
            // Add missing columns that are in the Agency model fillable but not in the migration
            $columns = [
                'description' => 'text',
                'website' => 'string',
                'city' => 'string',
                'country' => 'string',
                'logo' => 'string',
                'established_year' => 'integer',
                'number_of_agents' => 'integer',
                'specializations' => 'json',
                'coverage_areas' => 'json',
                'commission_rates' => 'json',
                'is_verified' => 'boolean',
                'is_active' => 'boolean',
                'rating' => 'decimal:2',
                'total_sales' => 'decimal:15,2',
                'total_properties' => 'integer',
                'social_media' => 'json',
                'contact_person' => 'string',
                'contact_person_title' => 'string',
                'contact_person_phone' => 'string',
                'contact_person_email' => 'string',
                'office_hours' => 'json',
                'languages_spoken' => 'json',
                'awards_certifications' => 'json',
                'company_description' => 'text',
                'mission_statement' => 'text',
                'vision_statement' => 'text',
                'core_values' => 'json',
                'services_offered' => 'json',
                'market_focus' => 'json',
                'target_audience' => 'json',
                'competitive_advantages' => 'json',
                'technology_stack' => 'json',
                'marketing_strategy' => 'json',
                'business_model' => 'json',
                'revenue_streams' => 'json',
                'operational_structure' => 'json',
                'growth_plans' => 'json',
                'partnerships' => 'json',
                'client_testimonials' => 'json',
                'case_studies' => 'json',
                'media_mentions' => 'json',
                'industry_recognition' => 'json',
                'regulatory_compliance' => 'json',
                'insurance_coverage' => 'json',
                'financial_performance' => 'json',
                'key_metrics' => 'json',
                'swot_analysis' => 'json',
                'market_position' => 'json',
                'brand_guidelines' => 'json',
                'quality_standards' => 'json',
                'training_programs' => 'json',
                'agent_support' => 'json',
                'commission_structure' => 'json',
                'benefits_packages' => 'json',
                'career_development' => 'json',
                'company_culture' => 'json',
                'employee_policies' => 'json',
                'performance_metrics' => 'json',
                'client_relationship_management' => 'json',
                'lead_generation_systems' => 'json',
                'crm_integration' => 'json',
                'document_management' => 'json',
                'transaction_management' => 'json',
                'listing_management' => 'json',
                'marketing_automation' => 'json',
                'analytics_reporting' => 'json',
                'compliance_monitoring' => 'json',
                'risk_management' => 'json',
                'data_security' => 'json',
                'privacy_protection' => 'json',
                'business_continuity' => 'json',
                'disaster_recovery' => 'json',
                'scalability_planning' => 'json',
                'innovation_initiatives' => 'json',
                'sustainability_practices' => 'json',
                'community_involvement' => 'json',
                'corporate_social_responsibility' => 'json',
                'environmental_impact' => 'json',
                'diversity_inclusion' => 'json',
                'ethical_standards' => 'json',
                'professional_development' => 'json',
                'industry_associations' => 'json',
                'network_affiliations' => 'json',
                'thought_leadership' => 'json',
                'research_contributions' => 'json',
                'best_practices' => 'json',
                'industry_trends' => 'json',
                'market_analysis' => 'json',
                'competitive_landscape' => 'json',
                'strategic_planning' => 'json',
                'operational_excellence' => 'json',
                'customer_experience' => 'json',
                'service_quality' => 'json',
                'brand_reputation' => 'json',
                'market_share' => 'json',
                'growth_rate' => 'json',
                'profitability' => 'json',
                'efficiency_metrics' => 'json',
                'satisfaction_scores' => 'json',
                'retention_rates' => 'json',
                'referral_rates' => 'json',
                'conversion_rates' => 'json',
                'lead_quality' => 'json',
                'deal_velocity' => 'json',
                'market_penetration' => 'json',
                'geographic_expansion' => 'json',
                'service_expansion' => 'json',
                'product_development' => 'json',
                'technology_adoption' => 'json',
                'process_optimization' => 'json',
                'cost_management' => 'json',
                'resource_allocation' => 'json',
                'capacity_planning' => 'json',
                'talent_acquisition' => 'json',
                'team_development' => 'json',
                'leadership_development' => 'json',
                'succession_planning' => 'json',
                'governance_structure' => 'json',
                'compliance_framework' => 'json',
                'audit_processes' => 'json',
                'internal_controls' => 'json',
                'risk_assessment' => 'json',
                'performance_monitoring' => 'json',
                'continuous_improvement' => 'json',
                'change_management' => 'json',
                'stakeholder_engagement' => 'json',
                'communication_strategy' => 'json',
                'crisis_management' => 'json',
                'reputation_management' => 'json',
                'public_relations' => 'json',
                'brand_management' => 'json',
                'digital_presence' => 'json',
                'online_marketing' => 'json',
                'social_media_strategy' => 'json',
                'content_strategy' => 'json',
                'seo_optimization' => 'json',
                'paid_advertising' => 'json',
                'email_marketing' => 'json',
                'event_marketing' => 'json',
                'partnership_marketing' => 'json',
                'referral_marketing' => 'json',
                'direct_marketing' => 'json',
                'offline_marketing' => 'json',
                'traditional_advertising' => 'json',
                'guerrilla_marketing' => 'json',
                'viral_marketing' => 'json',
                'influencer_marketing' => 'json',
                'affiliate_marketing' => 'json',
                'co_marketing' => 'json',
                'joint_ventures' => 'json',
                'strategic_alliances' => 'json',
                'distribution_channels' => 'json',
                'sales_channels' => 'json',
                'partnership_channels' => 'json',
                'direct_sales' => 'json',
                'indirect_sales' => 'json',
                'online_sales' => 'json',
                'offline_sales' => 'json',
                'hybrid_sales' => 'json',
                'multi_channel_sales' => 'json',
                'cross_channel_sales' => 'json',
                'omnichannel_sales' => 'json',
                'integrated_sales' => 'json',
                'seamless_sales' => 'json',
                'frictionless_sales' => 'json',
                'automated_sales' => 'json',
                'ai_powered_sales' => 'json',
                'data_driven_sales' => 'json',
                'predictive_sales' => 'json',
                'personalized_sales' => 'json',
                'contextual_sales' => 'json',
                'real_time_sales' => 'json',
                'dynamic_sales' => 'json',
                'adaptive_sales' => 'json',
                'intelligent_sales' => 'json',
                'smart_sales' => 'json',
                'automated_marketing' => 'json',
                'ai_marketing' => 'json',
                'data_marketing' => 'json',
                'predictive_marketing' => 'json',
                'personalized_marketing' => 'json',
                'contextual_marketing' => 'json',
                'real_time_marketing' => 'json',
                'dynamic_marketing' => 'json',
                'adaptive_marketing' => 'json',
                'intelligent_marketing' => 'json',
                'smart_marketing' => 'json',
                'automated_operations' => 'json',
                'ai_operations' => 'json',
                'data_operations' => 'json',
                'predictive_operations' => 'json',
                'personalized_operations' => 'json',
                'contextual_operations' => 'json',
                'real_time_operations' => 'json',
                'dynamic_operations' => 'json',
                'adaptive_operations' => 'json',
                'intelligent_operations' => 'json',
                'smart_operations' => 'json',
                'automated_management' => 'json',
                'ai_management' => 'json',
                'data_management' => 'json',
                'predictive_management' => 'json',
                'personalized_management' => 'json',
                'contextual_management' => 'json',
                'real_time_management' => 'json',
                'dynamic_management' => 'json',
                'adaptive_management' => 'json',
                'intelligent_management' => 'json',
                'smart_management' => 'json',
            ];
            
            foreach ($columns as $column => $type) {
                if (!Schema::hasColumn('agencies', $column)) {
                    if ($type === 'text') {
                        $table->text($column)->nullable();
                    } elseif ($type === 'string') {
                        $table->string($column)->nullable();
                    } elseif ($type === 'integer') {
                        $table->integer($column)->nullable();
                    } elseif ($type === 'boolean') {
                        $table->boolean($column)->default(false);
                    } elseif ($type === 'decimal:2') {
                        $table->decimal($column, 8, 2)->nullable();
                    } elseif ($type === 'decimal:15,2') {
                        $table->decimal($column, 15, 2)->nullable();
                    } elseif ($type === 'json') {
                        $table->json($column)->nullable();
                    }
                }
            }
        });
    }

    public function down()
    {
        Schema::table('agencies', function (Blueprint $table) {
            // Drop all the columns that were added (except the basic ones)
            $columns = [
                'deleted_at', 'description', 'website', 'city', 'country', 'logo', 'established_year', 'number_of_agents',
                'specializations', 'coverage_areas', 'commission_rates', 'is_verified', 'is_active', 'rating', 'total_sales',
                'total_properties', 'social_media', 'contact_person', 'contact_person_title', 'contact_person_phone',
                'contact_person_email', 'office_hours', 'languages_spoken', 'awards_certifications', 'company_description',
                'mission_statement', 'vision_statement', 'core_values', 'services_offered', 'market_focus', 'target_audience',
                'competitive_advantages', 'technology_stack', 'marketing_strategy', 'business_model', 'revenue_streams',
                'operational_structure', 'growth_plans', 'partnerships', 'client_testimonials', 'case_studies', 'media_mentions',
                'industry_recognition', 'regulatory_compliance', 'insurance_coverage', 'financial_performance', 'key_metrics',
                'swot_analysis', 'market_position', 'brand_guidelines', 'quality_standards', 'training_programs', 'agent_support',
                'commission_structure', 'benefits_packages', 'career_development', 'company_culture', 'employee_policies',
                'performance_metrics', 'client_relationship_management', 'lead_generation_systems', 'crm_integration',
                'document_management', 'transaction_management', 'listing_management', 'marketing_automation', 'analytics_reporting',
                'compliance_monitoring', 'risk_management', 'data_security', 'privacy_protection', 'business_continuity',
                'disaster_recovery', 'scalability_planning', 'innovation_initiatives', 'sustainability_practices',
                'community_involvement', 'corporate_social_responsibility', 'environmental_impact', 'diversity_inclusion',
                'ethical_standards', 'professional_development', 'industry_associations', 'network_affiliations', 'thought_leadership',
                'research_contributions', 'best_practices', 'industry_trends', 'market_analysis', 'competitive_landscape',
                'strategic_planning', 'operational_excellence', 'customer_experience', 'service_quality', 'brand_reputation',
                'market_share', 'growth_rate', 'profitability', 'efficiency_metrics', 'satisfaction_scores', 'retention_rates',
                'referral_rates', 'conversion_rates', 'lead_quality', 'deal_velocity', 'market_penetration', 'geographic_expansion',
                'service_expansion', 'product_development', 'technology_adoption', 'process_optimization', 'cost_management',
                'resource_allocation', 'capacity_planning', 'talent_acquisition', 'team_development', 'leadership_development',
                'succession_planning', 'governance_structure', 'compliance_framework', 'audit_processes', 'internal_controls',
                'risk_assessment', 'performance_monitoring', 'continuous_improvement', 'change_management', 'stakeholder_engagement',
                'communication_strategy', 'crisis_management', 'reputation_management', 'public_relations', 'brand_management',
                'digital_presence', 'online_marketing', 'social_media_strategy', 'content_strategy', 'seo_optimization',
                'paid_advertising', 'email_marketing', 'event_marketing', 'partnership_marketing', 'referral_marketing',
                'direct_marketing', 'offline_marketing', 'traditional_advertising', 'guerrilla_marketing', 'viral_marketing',
                'influencer_marketing', 'affiliate_marketing', 'co_marketing', 'joint_ventures', 'strategic_alliances',
                'distribution_channels', 'sales_channels', 'partnership_channels', 'direct_sales', 'indirect_sales',
                'online_sales', 'offline_sales', 'hybrid_sales', 'multi_channel_sales', 'cross_channel_sales', 'omnichannel_sales',
                'integrated_sales', 'seamless_sales', 'frictionless_sales', 'automated_sales', 'ai_powered_sales',
                'data_driven_sales', 'predictive_sales', 'personalized_sales', 'contextual_sales', 'real_time_sales',
                'dynamic_sales', 'adaptive_sales', 'intelligent_sales', 'smart_sales', 'automated_marketing',
                'ai_marketing', 'data_marketing', 'predictive_marketing', 'personalized_marketing', 'contextual_marketing',
                'real_time_marketing', 'dynamic_marketing', 'adaptive_marketing', 'intelligent_marketing', 'smart_marketing',
                'automated_operations', 'ai_operations', 'data_operations', 'predictive_operations', 'personalized_operations',
                'contextual_operations', 'real_time_operations', 'dynamic_operations', 'adaptive_operations',
                'intelligent_operations', 'smart_operations', 'automated_management', 'ai_management', 'data_management',
                'predictive_management', 'personalized_management', 'contextual_management', 'real_time_management',
                'dynamic_management', 'adaptive_management', 'intelligent_management', 'smart_management'
            ];
            
            foreach ($columns as $column) {
                if (Schema::hasColumn('agencies', $column)) {
                    $table->dropColumn($column);
                }
            }
        });
    }
};
