@extends('layouts.app')

@section('title', 'Appointments')

@section('content')
<div class="container mx-auto px-4 py-8">
    <div class="max-w-6xl mx-auto">
        <!-- Header -->
        <div class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <div class="flex justify-between items-center">
                <div>
                    <h1 class="text-2xl font-bold text-gray-800 mb-2">Appointments</h1>
                    <p class="text-gray-600">Manage your scheduled meetings</p>
                </div>
                <div class="flex items-center space-x-3">
                    <button onclick="createAppointment()" class="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 transition-colors">
                        <i class="fas fa-plus mr-2"></i>
                        New Appointment
                    </button>
                    <a href="{{ route('messages.inbox') }}" class="text-gray-600 hover:text-gray-800">
                        <i class="fas fa-arrow-left mr-2"></i>
                        Back to Messages
                    </a>
                </div>
            </div>
        </div>

        <!-- Calendar View -->
        <div class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <div class="flex justify-between items-center mb-6">
                <h2 class="text-lg font-semibold text-gray-800">Calendar</h2>
                <div class="flex items-center space-x-3">
                    <button onclick="previousMonth()" class="text-gray-600 hover:text-gray-800">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <span id="currentMonth" class="font-medium text-gray-800">{{ now()->format('F Y') }}</span>
                    <button onclick="nextMonth()" class="text-gray-600 hover:text-gray-800">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                    <button onclick="todayView()" class="bg-gray-200 text-gray-700 px-3 py-1 rounded-lg text-sm hover:bg-gray-300">
                        Today
                    </button>
                </div>
            </div>

            <!-- Calendar Grid -->
            <div class="grid grid-cols-7 gap-1 mb-4">
                <div class="text-center text-sm font-medium text-gray-600 py-2">Sun</div>
                <div class="text-center text-sm font-medium text-gray-600 py-2">Mon</div>
                <div class="text-center text-sm font-medium text-gray-600 py-2">Tue</div>
                <div class="text-center text-sm font-medium text-gray-600 py-2">Wed</div>
                <div class="text-center text-sm font-medium text-gray-600 py-2">Thu</div>
                <div class="text-center text-sm font-medium text-gray-600 py-2">Fri</div>
                <div class="text-center text-sm font-medium text-gray-600 py-2">Sat</div>
            </div>

            <div class="grid grid-cols-7 gap-1" id="calendarGrid">
                <!-- Calendar days will be generated by JavaScript -->
            </div>
        </div>

        <!-- Upcoming Appointments -->
        <div class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <div class="flex justify-between items-center mb-6">
                <h2 class="text-lg font-semibold text-gray-800">Upcoming Appointments</h2>
                <div class="flex items-center space-x-3">
                    <select onchange="filterAppointments(this.value)" class="px-3 py-2 border rounded-lg text-sm">
                        <option value="all">All</option>
                        <option value="today">Today</option>
                        <option value="week">This Week</option>
                        <option value="month">This Month</option>
                    </select>
                    <select onchange="sortAppointments(this.value)" class="px-3 py-2 border rounded-lg text-sm">
                        <option value="date">Sort by Date</option>
                        <option value="name">Sort by Name</option>
                        <option value="status">Sort by Status</option>
                    </select>
                </div>
            </div>

            <div class="space-y-4">
                @forelse ($appointments as $appointment)
                    <div class="border rounded-lg p-4 hover:shadow-md transition-shadow">
                        <div class="flex items-start justify-between">
                            <div class="flex items-start space-x-4">
                                <div class="bg-{{ $appointment->status === 'confirmed' ? 'green' : ($appointment->status === 'pending' ? 'yellow' : 'gray') }}-100 rounded-lg p-3">
                                    <i class="fas fa-calendar text-{{ $appointment->status === 'confirmed' ? 'green' : ($appointment->status === 'pending' ? 'yellow' : 'gray') }}-600"></i>
                                </div>
                                
                                <div class="flex-1">
                                    <h3 class="font-medium text-gray-800">{{ $appointment->title }}</h3>
                                    <div class="flex items-center space-x-4 text-sm text-gray-600 mt-1">
                                        <span><i class="fas fa-calendar-alt mr-1"></i>{{ $appointment->date->format('M j, Y') }}</span>
                                        <span><i class="fas fa-clock mr-1"></i>{{ $appointment->time->format('h:i A') }}</span>
                                        <span><i class="fas fa-hourglass-half mr-1"></i>{{ $appointment->duration }} minutes</span>
                                    </div>
                                    
                                    @if($appointment->participant)
                                        <div class="flex items-center space-x-2 mt-2">
                                            @if($appointment->participant->avatar)
                                                <img src="{{ $appointment->participant->avatar }}" alt="" class="w-6 h-6 rounded-full">
                                            @else
                                                <div class="w-6 h-6 bg-gray-300 rounded-full flex items-center justify-center">
                                                    <i class="fas fa-user text-gray-500 text-xs"></i>
                                                </div>
                                            @endif
                                            <span class="text-sm text-gray-600">{{ $appointment->participant->name }}</span>
                                        </div>
                                    @endif
                                    
                                    @if($appointment->notes)
                                        <p class="text-sm text-gray-600 mt-2">{{ $appointment->notes }}</p>
                                    @endif
                                </div>
                            </div>
                            
                            <div class="flex items-center space-x-2">
                                <span class="inline-flex px-2 py-1 text-xs font-semibold rounded-full
                                    @if($appointment->status === 'confirmed')
                                        bg-green-100 text-green-800
                                    @elseif($appointment->status === 'pending')
                                        bg-yellow-100 text-yellow-800
                                    @elseif($appointment->status === 'cancelled')
                                        bg-red-100 text-red-800
                                    @else
                                        bg-gray-100 text-gray-800
                                    @endif
                                ">
                                    {{ ucfirst($appointment->status) }}
                                </span>
                                
                                <div class="relative">
                                    <button onclick="showAppointmentActions({{ $appointment->id }})" class="text-gray-600 hover:text-gray-800">
                                        <i class="fas fa-ellipsis-v"></i>
                                    </button>
                                    
                                    <div id="appointmentActions{{ $appointment->id }}" class="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border hidden z-10">
                                        <button onclick="editAppointment({{ $appointment->id }})" class="w-full text-left px-4 py-2 text-sm hover:bg-gray-50">
                                            <i class="fas fa-edit mr-2"></i>Edit
                                        </button>
                                        <button onclick="rescheduleAppointment({{ $appointment->id }})" class="w-full text-left px-4 py-2 text-sm hover:bg-gray-50">
                                            <i class="fas fa-calendar-alt mr-2"></i>Reschedule
                                        </button>
                                        <button onclick="cancelAppointment({{ $appointment->id }})" class="w-full text-left px-4 py-2 text-sm hover:bg-gray-50 text-red-600">
                                            <i class="fas fa-times mr-2"></i>Cancel
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <!-- Action Buttons -->
                        <div class="flex space-x-3 mt-4">
                            @if($appointment->status === 'pending')
                                <button onclick="confirmAppointment({{ $appointment->id }})" class="bg-green-600 text-white px-3 py-1 rounded text-sm hover:bg-green-700 transition-colors">
                                    Confirm
                                </button>
                            @endif
                            
                            <button onclick="joinVideoCall({{ $appointment->id }})" class="bg-blue-600 text-white px-3 py-1 rounded text-sm hover:bg-blue-700 transition-colors">
                                <i class="fas fa-video mr-1"></i>Join Call
                            </button>
                            
                            <button onclick="sendReminder({{ $appointment->id }})" class="bg-gray-600 text-white px-3 py-1 rounded text-sm hover:bg-gray-700 transition-colors">
                                <i class="fas fa-bell mr-1"></i>Send Reminder
                            </button>
                        </div>
                    </div>
                @empty
                    <div class="text-center py-12">
                        <i class="fas fa-calendar text-6xl text-gray-300 mb-4"></i>
                        <h3 class="text-lg font-medium text-gray-900 mb-2">No appointments scheduled</h3>
                        <p class="text-gray-500 mb-4">Schedule your first appointment to get started</p>
                        <button onclick="createAppointment()" class="bg-purple-600 text-white px-6 py-3 rounded-lg hover:bg-purple-700 transition-colors">
                            <i class="fas fa-plus mr-2"></i>
                            Create Appointment
                        </button>
                    </div>
                @endforelse
            </div>
        </div>

        <!-- Statistics -->
        <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div class="bg-white rounded-lg shadow-sm p-6">
                <div class="flex items-center">
                    <div class="bg-blue-100 rounded-full p-3 mr-4">
                        <i class="fas fa-calendar-alt text-blue-600"></i>
                    </div>
                    <div>
                        <p class="text-sm text-gray-600">Total</p>
                        <p class="text-2xl font-bold text-gray-800">{{ $stats['total'] }}</p>
                    </div>
                </div>
            </div>
            
            <div class="bg-white rounded-lg shadow-sm p-6">
                <div class="flex items-center">
                    <div class="bg-green-100 rounded-full p-3 mr-4">
                        <i class="fas fa-check text-green-600"></i>
                    </div>
                    <div>
                        <p class="text-sm text-gray-600">Confirmed</p>
                        <p class="text-2xl font-bold text-gray-800">{{ $stats['confirmed'] }}</p>
                    </div>
                </div>
            </div>
            
            <div class="bg-white rounded-lg shadow-sm p-6">
                <div class="flex items-center">
                    <div class="bg-yellow-100 rounded-full p-3 mr-4">
                        <i class="fas fa-clock text-yellow-600"></i>
                    </div>
                    <div>
                        <p class="text-sm text-gray-600">Pending</p>
                        <p class="text-2xl font-bold text-gray-800">{{ $stats['pending'] }}</p>
                    </div>
                </div>
            </div>
            
            <div class="bg-white rounded-lg shadow-sm p-6">
                <div class="flex items-center">
                    <div class="bg-purple-100 rounded-full p-3 mr-4">
                        <i class="fas fa-video text-purple-600"></i>
                    </div>
                    <div>
                        <p class="text-sm text-gray-600">Today</p>
                        <p class="text-2xl font-bold text-gray-800">{{ $stats['today'] }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Create Appointment Modal -->
<div id="appointmentModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 hidden">
    <div class="bg-white rounded-lg p-6 max-w-md mx-4 w-full">
        <h3 class="text-lg font-semibold text-gray-800 mb-4">Create Appointment</h3>
        
        <form onsubmit="saveAppointment(event)">
            <div class="space-y-4">
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Title</label>
                    <input type="text" id="appointmentTitle" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500">
                </div>
                
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Participant</label>
                    <select id="appointmentParticipant" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500">
                        <option value="">Select participant</option>
                        @foreach ($users as $user)
                            <option value="{{ $user->id }}">{{ $user->name }}</option>
                        @endforeach
                    </select>
                </div>
                
                <div class="grid grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Date</label>
                        <input type="date" id="appointmentDate" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500">
                    </div>
                    
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Time</label>
                        <input type="time" id="appointmentTime" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500">
                    </div>
                </div>
                
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Duration</label>
                    <select id="appointmentDuration" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500">
                        <option value="30">30 minutes</option>
                        <option value="60">1 hour</option>
                        <option value="90">1.5 hours</option>
                        <option value="120">2 hours</option>
                    </select>
                </div>
                
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Type</label>
                    <select id="appointmentType" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500">
                        <option value="video">Video Call</option>
                        <option value="voice">Voice Call</option>
                        <option value="in-person">In Person</option>
                        <option value="phone">Phone Call</option>
                    </select>
                </div>
                
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Notes</label>
                    <textarea id="appointmentNotes" rows="3" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"></textarea>
                </div>
                
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Reminder</label>
                    <select id="appointmentReminder" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500">
                        <option value="15">15 minutes before</option>
                        <option value="30">30 minutes before</option>
                        <option value="60">1 hour before</option>
                        <option value="1440">1 day before</option>
                    </select>
                </div>
            </div>
            
            <div class="flex justify-end space-x-3 mt-6">
                <button type="button" onclick="closeAppointmentModal()" class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
                    Cancel
                </button>
                <button type="submit" class="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 transition-colors">
                    Create Appointment
                </button>
            </div>
        </form>
    </div>
</div>

<script>
let currentMonth = new Date().getMonth();
let currentYear = new Date().getFullYear();

function generateCalendar() {
    const firstDay = new Date(currentYear, currentMonth, 1).getDay();
    const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
    const today = new Date();
    
    const grid = document.getElementById('calendarGrid');
    grid.innerHTML = '';
    
    // Empty cells for days before month starts
    for (let i = 0; i < firstDay; i++) {
        grid.innerHTML += '<div class="p-2"></div>';
    }
    
    // Days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const isToday = today.getDate() === day && today.getMonth() === currentMonth && today.getFullYear() === currentYear;
        const hasAppointments = checkAppointmentsForDay(day);
        
        grid.innerHTML += `
            <div class="p-2 border rounded-lg hover:bg-gray-50 cursor-pointer ${isToday ? 'bg-blue-50 border-blue-500' : 'border-gray-200'}" onclick="selectDate(${day})">
                <div class="text-sm ${isToday ? 'font-bold text-blue-600' : 'text-gray-800'}">${day}</div>
                ${hasAppointments ? '<div class="w-2 h-2 bg-purple-500 rounded-full mx-auto mt-1"></div>' : ''}
            </div>
        `;
    }
    
    // Update month display
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    document.getElementById('currentMonth').textContent = monthNames[currentMonth] + ' ' + currentYear;
}

function checkAppointmentsForDay(day) {
    // Check if there are appointments for this day
    // This would typically check against your appointments data
    return Math.random() > 0.8; // Random for demo
}

function previousMonth() {
    currentMonth--;
    if (currentMonth < 0) {
        currentMonth = 11;
        currentYear--;
    }
    generateCalendar();
}

function nextMonth() {
    currentMonth++;
    if (currentMonth > 11) {
        currentMonth = 0;
        currentYear++;
    }
    generateCalendar();
}

function todayView() {
    currentMonth = new Date().getMonth();
    currentYear = new Date().getFullYear();
    generateCalendar();
}

function selectDate(day) {
    // Set the date in the appointment form
    const date = new Date(currentYear, currentMonth, day);
    document.getElementById('appointmentDate').value = date.toISOString().split('T')[0];
    
    // Open appointment modal
    createAppointment();
}

function createAppointment() {
    document.getElementById('appointmentModal').classList.remove('hidden');
}

function closeAppointmentModal() {
    document.getElementById('appointmentModal').classList.add('hidden');
}

function saveAppointment(event) {
    event.preventDefault();
    
    const title = document.getElementById('appointmentTitle').value;
    const participant = document.getElementById('appointmentParticipant').value;
    const date = document.getElementById('appointmentDate').value;
    const time = document.getElementById('appointmentTime').value;
    const duration = document.getElementById('appointmentDuration').value;
    const type = document.getElementById('appointmentType').value;
    const notes = document.getElementById('appointmentNotes').value;
    const reminder = document.getElementById('appointmentReminder').value;
    
    fetch('/messages/appointments', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
        },
        body: JSON.stringify({
            title: title,
            participant_id: participant,
            date: date,
            time: time,
            duration: duration,
            type: type,
            notes: notes,
            reminder_minutes: reminder
        })
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            closeAppointmentModal();
            location.reload();
        }
    })
    .catch(error => {
        console.error('Error:', error);
    });
}

function showAppointmentActions(appointmentId) {
    const actions = document.getElementById('appointmentActions' + appointmentId);
    
    // Hide all other action menus
    document.querySelectorAll('[id^="appointmentActions"]').forEach(menu => {
        if (menu.id !== 'appointmentActions' + appointmentId) {
            menu.classList.add('hidden');
        }
    });
    
    actions.classList.toggle('hidden');
}

function editAppointment(appointmentId) {
    window.location.href = '/messages/appointments/' + appointmentId + '/edit';
}

function rescheduleAppointment(appointmentId) {
    window.location.href = '/messages/appointments/' + appointmentId + '/reschedule';
}

function cancelAppointment(appointmentId) {
    if (confirm('Are you sure you want to cancel this appointment?')) {
        fetch('/messages/appointments/' + appointmentId + '/cancel', {
            method: 'POST',
            headers: {
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                location.reload();
            }
        })
        .catch(error => {
            console.error('Error:', error);
        });
    }
}

function confirmAppointment(appointmentId) {
    fetch('/messages/appointments/' + appointmentId + '/confirm', {
        method: 'POST',
        headers: {
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
        }
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            location.reload();
        }
    })
    .catch(error => {
        console.error('Error:', error);
    });
}

function joinVideoCall(appointmentId) {
    window.location.href = '/messages/video-call/appointment/' + appointmentId;
}

function sendReminder(appointmentId) {
    fetch('/messages/appointments/' + appointmentId + '/reminder', {
        method: 'POST',
        headers: {
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
        }
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            alert('Reminder sent successfully!');
        }
    })
    .catch(error => {
        console.error('Error:', error);
    });
}

function filterAppointments(filter) {
    window.location.href = '?filter=' + filter;
}

function sortAppointments(sort) {
    window.location.href = '?sort=' + sort;
}

// Initialize calendar
generateCalendar();

// Close dropdowns when clicking outside
document.addEventListener('click', function(event) {
    if (!event.target.matches('[onclick*="showAppointmentActions"]')) {
        document.querySelectorAll('[id^="appointmentActions"]').forEach(menu => {
            menu.classList.add('hidden');
        });
    }
});
</script>
@endsection
