@extends('layouts.app')

@section('title', 'Calendar')

@section('content')
<div class="container mx-auto px-4 py-8">
    <div class="max-w-6xl mx-auto">
        <!-- Header -->
        <div class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <div class="flex justify-between items-center">
                <div>
                    <h1 class="text-2xl font-bold text-gray-800 mb-2">Calendar</h1>
                    <p class="text-gray-600">View and manage your schedule</p>
                </div>
                <div class="flex items-center space-x-3">
                    <button onclick="createAppointment()" class="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 transition-colors">
                        <i class="fas fa-plus mr-2"></i>
                        New Event
                    </button>
                    <a href="{{ route('messages.inbox') }}" class="text-gray-600 hover:text-gray-800">
                        <i class="fas fa-arrow-left mr-2"></i>
                        Back to Messages
                    </a>
                </div>
            </div>
        </div>

        <!-- Calendar Navigation -->
        <div class="bg-white rounded-lg shadow-sm p-6 mb-6">
            <div class="flex justify-between items-center mb-6">
                <div class="flex items-center space-x-4">
                    <button onclick="previousMonth()" class="text-gray-600 hover:text-gray-800">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <h2 id="currentMonth" class="text-xl font-semibold text-gray-800">{{ now()->format('F Y') }}</h2>
                    <button onclick="nextMonth()" class="text-gray-600 hover:text-gray-800">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
                
                <div class="flex items-center space-x-3">
                    <button onclick="todayView()" class="bg-gray-200 text-gray-700 px-3 py-1 rounded-lg text-sm hover:bg-gray-300">
                        Today
                    </button>
                    <select onchange="changeView(this.value)" class="px-3 py-2 border rounded-lg text-sm">
                        <option value="month">Month</option>
                        <option value="week">Week</option>
                        <option value="day">Day</option>
                    </select>
                    <button onclick="exportCalendar()" class="text-gray-600 hover:text-gray-800">
                        <i class="fas fa-download"></i>
                    </button>
                </div>
            </div>

            <!-- Calendar Grid -->
            <div class="grid grid-cols-7 gap-px bg-gray-200">
                <!-- Day Headers -->
                <div class="bg-gray-50 p-3 text-center text-sm font-medium text-gray-700">Sunday</div>
                <div class="bg-gray-50 p-3 text-center text-sm font-medium text-gray-700">Monday</div>
                <div class="bg-gray-50 p-3 text-center text-sm font-medium text-gray-700">Tuesday</div>
                <div class="bg-gray-50 p-3 text-center text-sm font-medium text-gray-700">Wednesday</div>
                <div class="bg-gray-50 p-3 text-center text-sm font-medium text-gray-700">Thursday</div>
                <div class="bg-gray-50 p-3 text-center text-sm font-medium text-gray-700">Friday</div>
                <div class="bg-gray-50 p-3 text-center text-sm font-medium text-gray-700">Saturday</div>
                
                <!-- Calendar Days -->
                <div id="calendarGrid" class="col-span-7 grid grid-cols-7 gap-px">
                    <!-- Days will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Upcoming Events -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <!-- Today's Events -->
            <div class="bg-white rounded-lg shadow-sm p-6">
                <div class="flex justify-between items-center mb-4">
                    <h3 class="text-lg font-semibold text-gray-800">Today's Events</h3>
                    <span class="bg-blue-100 text-blue-800 px-2 py-1 rounded-full text-xs">
                        {{ $todayEvents->count() }} events
                    </span>
                </div>
                
                <div class="space-y-3">
                    @forelse ($todayEvents as $event)
                        <div class="flex items-start space-x-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 cursor-pointer" onclick="viewEvent({{ $event->id }})">
                            <div class="bg-{{ $event->type === 'appointment' ? 'purple' : ($event->type === 'meeting' ? 'blue' : 'green') }}-100 rounded-lg p-2">
                                <i class="fas fa-{{ $event->type === 'appointment' ? 'calendar' : ($event->type === 'meeting' ? 'users' : 'phone') }} text-{{ $event->type === 'appointment' ? 'purple' : ($event->type === 'meeting' ? 'blue' : 'green') }}-600 text-sm"></i>
                            </div>
                            
                            <div class="flex-1">
                                <h4 class="font-medium text-gray-800">{{ $event->title }}</h4>
                                <div class="flex items-center space-x-3 text-sm text-gray-600 mt-1">
                                    <span><i class="fas fa-clock mr-1"></i>{{ $event->start_time->format('h:i A') }}</span>
                                    @if($event->end_time)
                                        <span>- {{ $event->end_time->format('h:i A') }}</span>
                                    @endif
                                    @if($event->participant)
                                        <span><i class="fas fa-user mr-1"></i>{{ $event->participant->name }}</span>
                                    @endif
                                </div>
                            </div>
                            
                            <div class="flex items-center space-x-2">
                                @if($event->type === 'appointment')
                                    <button onclick="joinVideoCall({{ $event->id }})" class="text-blue-600 hover:text-blue-800">
                                        <i class="fas fa-video"></i>
                                    </button>
                                @endif
                                <button onclick="editEvent({{ $event->id }})" class="text-gray-600 hover:text-gray-800">
                                    <i class="fas fa-edit"></i>
                                </button>
                            </div>
                        </div>
                    @empty
                        <div class="text-center py-8">
                            <i class="fas fa-calendar-day text-4xl text-gray-300 mb-3"></i>
                            <p class="text-gray-500">No events today</p>
                        </div>
                    @endforelse
                </div>
            </div>

            <!-- This Week's Events -->
            <div class="bg-white rounded-lg shadow-sm p-6">
                <div class="flex justify-between items-center mb-4">
                    <h3 class="text-lg font-semibold text-gray-800">This Week</h3>
                    <span class="bg-purple-100 text-purple-800 px-2 py-1 rounded-full text-xs">
                        {{ $weekEvents->count() }} events
                    </span>
                </div>
                
                <div class="space-y-3">
                    @forelse ($weekEvents as $event)
                        <div class="flex items-start space-x-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 cursor-pointer" onclick="viewEvent({{ $event->id }})">
                            <div class="bg-{{ $event->type === 'appointment' ? 'purple' : ($event->type === 'meeting' ? 'blue' : 'green') }}-100 rounded-lg p-2">
                                <i class="fas fa-{{ $event->type === 'appointment' ? 'calendar' : ($event->type === 'meeting' ? 'users' : 'phone') }} text-{{ $event->type === 'appointment' ? 'purple' : ($event->type === 'meeting' ? 'blue' : 'green') }}-600 text-sm"></i>
                            </div>
                            
                            <div class="flex-1">
                                <h4 class="font-medium text-gray-800">{{ $event->title }}</h4>
                                <div class="flex items-center space-x-3 text-sm text-gray-600 mt-1">
                                    <span><i class="fas fa-calendar mr-1"></i>{{ $event->date->format('M j') }}</span>
                                    <span><i class="fas fa-clock mr-1"></i>{{ $event->start_time->format('h:i A') }}</span>
                                    @if($event->participant)
                                        <span><i class="fas fa-user mr-1"></i>{{ $event->participant->name }}</span>
                                    @endif
                                </div>
                            </div>
                            
                            <div class="flex items-center space-x-2">
                                <button onclick="editEvent({{ $event->id }})" class="text-gray-600 hover:text-gray-800">
                                    <i class="fas fa-edit"></i>
                                </button>
                            </div>
                        </div>
                    @empty
                        <div class="text-center py-8">
                            <i class="fas fa-calendar-week text-4xl text-gray-300 mb-3"></i>
                            <p class="text-gray-500">No events this week</p>
                        </div>
                    @endforelse
                </div>
            </div>
        </div>

        <!-- Event Categories -->
        <div class="bg-white rounded-lg shadow-sm p-6 mt-6">
            <h3 class="text-lg font-semibold text-gray-800 mb-4">Event Categories</h3>
            
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div class="flex items-center justify-between p-4 border rounded-lg">
                    <div class="flex items-center space-x-3">
                        <div class="bg-purple-100 rounded-lg p-2">
                            <i class="fas fa-calendar text-purple-600"></i>
                        </div>
                        <div>
                            <h4 class="font-medium text-gray-800">Appointments</h4>
                            <p class="text-sm text-gray-600">{{ $stats['appointments'] }} events</p>
                        </div>
                    </div>
                    <button onclick="filterByCategory('appointment')" class="text-purple-600 hover:text-purple-800">
                        <i class="fas fa-filter"></i>
                    </button>
                </div>
                
                <div class="flex items-center justify-between p-4 border rounded-lg">
                    <div class="flex items-center space-x-3">
                        <div class="bg-blue-100 rounded-lg p-2">
                            <i class="fas fa-users text-blue-600"></i>
                        </div>
                        <div>
                            <h4 class="font-medium text-gray-800">Meetings</h4>
                            <p class="text-sm text-gray-600">{{ $stats['meetings'] }} events</p>
                        </div>
                    </div>
                    <button onclick="filterByCategory('meeting')" class="text-blue-600 hover:text-blue-800">
                        <i class="fas fa-filter"></i>
                    </button>
                </div>
                
                <div class="flex items-center justify-between p-4 border rounded-lg">
                    <div class="flex items-center space-x-3">
                        <div class="bg-green-100 rounded-lg p-2">
                            <i class="fas fa-phone text-green-600"></i>
                        </div>
                        <div>
                            <h4 class="font-medium text-gray-800">Calls</h4>
                            <p class="text-sm text-gray-600">{{ $stats['calls'] }} events</p>
                        </div>
                    </div>
                    <button onclick="filterByCategory('call')" class="text-green-600 hover:text-green-800">
                        <i class="fas fa-filter"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Event Details Modal -->
<div id="eventModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 hidden">
    <div class="bg-white rounded-lg p-6 max-w-md mx-4 w-full">
        <h3 class="text-lg font-semibold text-gray-800 mb-4">Event Details</h3>
        
        <div id="eventDetails" class="space-y-4">
            <!-- Event details will be inserted here -->
        </div>
        
        <div class="flex justify-end space-x-3 mt-6">
            <button onclick="closeEventModal()" class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
                Close
            </button>
            <button onclick="editEvent()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
                Edit Event
            </button>
        </div>
    </div>
</div>

<script>
let currentMonth = new Date().getMonth();
let currentYear = new Date().getFullYear();
let currentView = 'month';

function generateCalendar() {
    const firstDay = new Date(currentYear, currentMonth, 1).getDay();
    const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
    const today = new Date();
    
    const grid = document.getElementById('calendarGrid');
    grid.innerHTML = '';
    
    // Empty cells for days before month starts
    for (let i = 0; i < firstDay; i++) {
        grid.innerHTML += '<div class="bg-white p-2 min-h-[80px]"></div>';
    }
    
    // Days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const isToday = today.getDate() === day && today.getMonth() === currentMonth && today.getFullYear() === currentYear;
        const events = getEventsForDay(day);
        const isWeekend = new Date(currentYear, currentMonth, day).getDay() === 0 || new Date(currentYear, currentMonth, day).getDay() === 6;
        
        let dayHtml = `
            <div class="bg-white p-2 min-h-[80px] border-r border-b ${isToday ? 'bg-blue-50' : ''} ${isWeekend ? 'bg-gray-50' : ''} hover:bg-gray-50 cursor-pointer" onclick="selectDate(${day})">
                <div class="text-sm ${isToday ? 'font-bold text-blue-600' : 'text-gray-800'}">${day}</div>
        `;
        
        if (events.length > 0) {
            dayHtml += '<div class="mt-1 space-y-1">';
            events.slice(0, 3).forEach(event => {
                const colorClass = event.type === 'appointment' ? 'bg-purple-500' : (event.type === 'meeting' ? 'bg-blue-500' : 'bg-green-500');
                dayHtml += `<div class="text-xs ${colorClass} text-white px-1 py-0.5 rounded truncate">${event.title}</div>`;
            });
            if (events.length > 3) {
                dayHtml += `<div class="text-xs text-gray-500">+${events.length - 3} more</div>`;
            }
            dayHtml += '</div>';
        }
        
        dayHtml += '</div>';
        grid.innerHTML += dayHtml;
    }
    
    // Update month display
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    document.getElementById('currentMonth').textContent = monthNames[currentMonth] + ' ' + currentYear;
}

function getEventsForDay(day) {
    // This would typically fetch events from your data
    // For demo purposes, return random events
    const events = [];
    const eventCount = Math.floor(Math.random() * 3);
    const types = ['appointment', 'meeting', 'call'];
    
    for (let i = 0; i < eventCount; i++) {
        events.push({
            id: day + '_' + i,
            title: 'Event ' + (i + 1),
            type: types[Math.floor(Math.random() * types.length)]
        });
    }
    
    return events;
}

function previousMonth() {
    currentMonth--;
    if (currentMonth < 0) {
        currentMonth = 11;
        currentYear--;
    }
    generateCalendar();
}

function nextMonth() {
    currentMonth++;
    if (currentMonth > 11) {
        currentMonth = 0;
        currentYear++;
    }
    generateCalendar();
}

function todayView() {
    currentMonth = new Date().getMonth();
    currentYear = new Date().getFullYear();
    generateCalendar();
}

function changeView(view) {
    currentView = view;
    // Implement different view types
    console.log('Changing view to:', view);
}

function selectDate(day) {
    const date = new Date(currentYear, currentMonth, day);
    document.getElementById('appointmentDate').value = date.toISOString().split('T')[0];
    createAppointment();
}

function createAppointment() {
    // This would open the appointment creation modal
    window.location.href = '/messages/appointments/create';
}

function viewEvent(eventId) {
    // This would fetch and display event details
    console.log('Viewing event:', eventId);
    document.getElementById('eventModal').classList.remove('hidden');
}

function closeEventModal() {
    document.getElementById('eventModal').classList.add('hidden');
}

function editEvent(eventId) {
    window.location.href = '/messages/appointments/' + eventId + '/edit';
}

function joinVideoCall(eventId) {
    window.location.href = '/messages/video-call/appointment/' + eventId;
}

function filterByCategory(category) {
    window.location.href = '?category=' + category;
}

function exportCalendar() {
    window.location.href = '/messages/calendar/export';
}

// Initialize calendar
generateCalendar();

// Auto-refresh every minute
setInterval(generateCalendar, 60000);
</script>
@endsection
